import "server-only";
import type {SupabaseClient} from "@supabase/supabase-js";
export type ActorContext={actorId:string;agencyId:string;role:"owner"|"admin"|"operator"|"viewer"};
export type AuthorizationSession={id:string;agency_id:string;initiated_by_actor_id:string;status:string;expires_at:string;pkce_credential_ref:string;return_path:string|null};
const unwrap=<T>(data:T|null,error:{message:string}|null,code:string)=>{if(error||data===null)throw new Error(code);return data};
export class ConnectionHubRepository{
 private readonly db:SupabaseClient;
 constructor(db:SupabaseClient){this.db = db;}
 async resolveActor(email:string){const {data,error}=await this.db.rpc("platform_resolve_actor",{p_email:email.toLowerCase().trim()});const row=Array.isArray(data)?data[0]:data;if(error||!row||typeof row.actor_id!=="string"||typeof row.agency_id!=="string")throw new Error("actor_forbidden");return {actorId:row.actor_id,agencyId:row.agency_id,role:row.role} as ActorContext;}
 async createAuthorizationSession(input:{actor:ActorContext;stateHash:string;pkceReference:string;returnPath:string;expiresAt:string}){const {data,error}=await this.db.from("integration_authorization_sessions").insert({agency_id:input.actor.agencyId,provider:"google",initiated_by_actor_id:input.actor.actorId,state_hash:input.stateHash,pkce_credential_ref:input.pkceReference,return_path:input.returnPath,expires_at:input.expiresAt}).select("id").single();return unwrap(data,error,"authorization_session_create_failed");}
 async findAuthorizationSession(actor:ActorContext,stateHash:string){const {data,error}=await this.db.from("integration_authorization_sessions").select("id,agency_id,initiated_by_actor_id,status,expires_at,pkce_credential_ref,return_path").eq("agency_id",actor.agencyId).eq("provider","google").eq("state_hash",stateHash).maybeSingle();return unwrap(data,error,"authorization_session_invalid") as AuthorizationSession;}
 async claimAuthorizationSession(sessionId:string,agencyId:string){const {data,error}=await this.db.from("integration_authorization_sessions").update({status:"processing"}).eq("id",sessionId).eq("agency_id",agencyId).eq("status","pending").gt("expires_at",new Date().toISOString()).select("id").maybeSingle();return unwrap(data,error,"authorization_session_already_used");}
 async completeAuthorizationSession(sessionId:string,agencyId:string,status:"completed"|"failed"){const {data,error}=await this.db.from("integration_authorization_sessions").update({status,completed_at:new Date().toISOString()}).eq("id",sessionId).eq("agency_id",agencyId).eq("status","processing").select("id").maybeSingle();return unwrap(data,error,"authorization_session_already_used");}
 async upsertGoogleConnection(input:{actor:ActorContext;credentialReference:string;scope:string}){const existing=await this.db.from("integration_connections").select("id").eq("agency_id",input.actor.agencyId).eq("provider","google").neq("status","disconnected").maybeSingle();if(existing.error)throw new Error("connection_lookup_failed");const values={agency_id:input.actor.agencyId,provider:"google",label:"Google",responsible_actor_id:input.actor.actorId,credential_ref:input.credentialReference,status:"connected",sync_status:"syncing",last_error_code:null,metadata:{authorized_scope:input.scope}};if(existing.data){const {data,error}=await this.db.from("integration_connections").update(values).eq("id",existing.data.id).eq("agency_id",input.actor.agencyId).select("id").single();return unwrap(data,error,"connection_update_failed") as {id:string};}const {data,error}=await this.db.from("integration_connections").insert(values).select("id").single();return unwrap(data,error,"connection_create_failed") as {id:string};}
 async activateGbpCapability(actor:ActorContext,connectionId:string){const {error}=await this.db.from("integration_connection_capabilities").upsert({agency_id:actor.agencyId,connection_id:connectionId,capability:"google_business_profile",status:"active",granted_scopes:["https://www.googleapis.com/auth/business.manage"]},{onConflict:"connection_id,capability"});if(error)throw new Error("capability_update_failed");}
 async saveResources(actor:ActorContext,connectionId:string,resources:Array<{capability:string;resourceType:string;externalKey:string;displayName:string;parentKey?:string;metadata:Record<string,unknown>}>){for(const resource of resources){const {error}=await this.db.from("integration_external_resources").upsert({agency_id:actor.agencyId,connection_id:connectionId,capability:resource.capability,resource_type:resource.resourceType,external_resource_key:resource.externalKey,display_name:resource.displayName,parent_external_resource_key:resource.parentKey??null,status:"active",metadata:resource.metadata,last_discovered_at:new Date().toISOString()},{onConflict:"connection_id,capability,external_resource_key"});if(error)throw new Error("resource_persistence_failed");}}
 async markSync(actor:ActorContext,connectionId:string,status:"success"|"error",errorCode?:string){const now=new Date().toISOString();const values=status==="success"?{status:"connected",sync_status:"success",last_sync_at:now,last_success_at:now,last_error_code:null}:{status:"error",sync_status:"error",last_sync_at:now,last_error_code:errorCode??"sync_failed"};const {error}=await this.db.from("integration_connections").update(values).eq("agency_id",actor.agencyId).eq("id",connectionId);if(error)throw new Error("connection_health_update_failed");}
 async snapshot(actor:ActorContext){const [connections,resources,bindings]=await Promise.all([this.db.from("integration_connections").select("id,provider,label,status,last_sync_at,last_success_at,sync_status,last_error_code").eq("agency_id",actor.agencyId),this.db.from("integration_external_resources").select("id,connection_id,capability,resource_type,display_name,parent_external_resource_key,status,metadata,last_discovered_at").eq("agency_id",actor.agencyId),this.db.from("client_resource_bindings").select("id,client_id,resource_id,capability,status").eq("agency_id",actor.agencyId).eq("status","active")]);if(connections.error||resources.error||bindings.error)throw new Error("connection_hub_unavailable");return {connections:connections.data??[],resources:resources.data??[],bindings:bindings.data??[]};}
 async googleConnection(actor:ActorContext,connectionId?:string){let query=this.db.from("integration_connections").select("id,credential_ref,status").eq("agency_id",actor.agencyId).eq("provider","google").neq("status","disconnected");if(connectionId)query=query.eq("id",connectionId);const {data,error}=await query.limit(1).maybeSingle();if(error)throw new Error("connection_lookup_failed");return data as {id:string;credential_ref:string;status:string}|null;}
 async clientConnection(actor:ActorContext,clientId:string,capability:string){const client=await this.db.from("clients").select("id").eq("agency_id",actor.agencyId).eq("id",clientId).maybeSingle();if(client.error||!client.data)throw new Error("client_not_found");const {data,error}=await this.db.from("client_resource_bindings").select("id,resource_id,capability,status,integration_external_resources!inner(id,display_name,status,connection_id,integration_connections!inner(id,status,last_sync_at,sync_status))").eq("agency_id",actor.agencyId).eq("client_id",clientId).eq("capability",capability).eq("status","active").maybeSingle();if(error)throw new Error("binding_lookup_failed");return data;}
 async bindResource(actor:ActorContext,input:{clientId:string;resourceId:string;capability:string}){if(!["owner","admin","operator"].includes(actor.role))throw new Error("actor_forbidden");const [client,resource]=await Promise.all([this.db.from("clients").select("id").eq("agency_id",actor.agencyId).eq("id",input.clientId).maybeSingle(),this.db.from("integration_external_resources").select("id,capability,status,connection_id").eq("agency_id",actor.agencyId).eq("id",input.resourceId).maybeSingle()]);if(client.error||!client.data)throw new Error("client_not_found");if(resource.error||!resource.data||resource.data.status!=="active"||resource.data.capability!==input.capability)throw new Error("resource_not_available");const {data,error}=await this.db.from("client_resource_bindings").upsert({agency_id:actor.agencyId,client_id:input.clientId,resource_id:input.resourceId,capability:input.capability,status:"active",created_by_actor_id:actor.actorId},{onConflict:"client_id,resource_id,capability"}).select("id").single();return unwrap(data,error,"binding_failed");}
 async audit(actor:ActorContext,action:string,targetType:string,targetId?:string,payload:Record<string,unknown>={}){await this.db.from("audit_events").insert({agency_id:actor.agencyId,actor_user_id:null,action,target_type:targetType,target_id:targetId??null,payload:{actor_id:actor.actorId,...payload}});}
}
