import "server-only";
import {SupabaseVaultCredentialStore,type StoredGoogleCredential} from "./credential-store";
import {GoogleProviderAdapter,GoogleProviderError} from "./google-adapter";
import {createOAuthProof,hashOAuthState,isAuthorizationSessionValid,safeReturnPath} from "./oauth-security";
import {ConnectionHubRepository,type ActorContext} from "./repository";
import {createSupabaseAdmin} from "./supabase-admin";
import {getGoogleOAuthConfig,getGoogleProviderAvailability} from "./server-config";
export type HubRuntime={repository:ConnectionHubRepository;credentials:SupabaseVaultCredentialStore;google:GoogleProviderAdapter};
export function createHubRuntime():HubRuntime|null{const db=createSupabaseAdmin(),config=getGoogleOAuthConfig();if(!db||!config)return null;return {repository:new ConnectionHubRepository(db),credentials:new SupabaseVaultCredentialStore(db),google:new GoogleProviderAdapter(config)};}
export function googleConfigurationStatus(){const clientIdConfigured=Boolean(process.env.GOOGLE_OAUTH_CLIENT_ID?.trim()),clientSecretConfigured=Boolean(process.env.GOOGLE_OAUTH_CLIENT_SECRET?.trim()),redirectUriConfigured=Boolean(process.env.GOOGLE_OAUTH_REDIRECT_URI?.trim()),providerAvailability=getGoogleProviderAvailability();return {configured:providerAvailability==="ready_for_oauth"&&Boolean(getGoogleOAuthConfig()),providerAvailability,connectionManagementMode:"platform_managed" as const,health:providerAvailability==="pending_provider_approval"?"provider_pending" as const:providerAvailability==="not_configured"?"configuration_required" as const:"unknown" as const,persistenceConfigured:Boolean(createSupabaseAdmin()),clientIdConfigured,clientSecretConfigured,redirectUriConfigured,scope:"https://www.googleapis.com/auth/business.manage"};}
export async function startGoogleAuthorization(runtime:HubRuntime,email:string,returnPath:string|null){const actor=await runtime.repository.resolveActor(email),proof=createOAuthProof(),pkceReference=await runtime.credentials.storeSecret(proof.verifier,"Google OAuth PKCE verifier; short-lived");await runtime.repository.createAuthorizationSession({actor,stateHash:proof.stateHash,pkceReference,returnPath:safeReturnPath(returnPath),expiresAt:new Date(Date.now()+10*60_000).toISOString()});await runtime.repository.audit(actor,"google.authorization_started","integration_authorization_session",undefined,{provider:"google",capability:"google_business_profile"});return runtime.google.createAuthorizationUrl({state:proof.state,codeChallenge:proof.challenge});}
export async function failGoogleAuthorization(runtime:HubRuntime,input:{email:string;state:string;reason:string}){const actor=await runtime.repository.resolveActor(input.email),session=await runtime.repository.findAuthorizationSession(actor,hashOAuthState(input.state));if(!isAuthorizationSessionValid(session,actor.actorId))throw new Error("authorization_session_invalid");await runtime.repository.claimAuthorizationSession(session.id,actor.agencyId);await runtime.repository.completeAuthorizationSession(session.id,actor.agencyId,"failed");await runtime.credentials.revokeSecret(session.pkce_credential_ref).catch(()=>undefined);await runtime.repository.audit(actor,"google.authorization_failed","integration_authorization_session",session.id,{error_code:input.reason});}
export async function finishGoogleAuthorization(runtime:HubRuntime,input:{email:string;state:string;code:string}){const actor=await runtime.repository.resolveActor(input.email),session=await runtime.repository.findAuthorizationSession(actor,hashOAuthState(input.state));if(!isAuthorizationSessionValid(session,actor.actorId))throw new Error("authorization_session_invalid");await runtime.repository.claimAuthorizationSession(session.id,actor.agencyId);try{const verifier=await runtime.credentials.getSecret(session.pkce_credential_ref);const tokens=await runtime.google.exchangeAuthorizationCode(input.code,verifier);if(!tokens.refreshToken)throw new Error("refresh_token_missing");const credential:StoredGoogleCredential={refreshToken:tokens.refreshToken,accessToken:tokens.accessToken,expiresAt:tokens.expiresAt,scope:tokens.scope,tokenType:tokens.tokenType};const credentialReference=await runtime.credentials.storeSecret(JSON.stringify(credential),`Google OAuth credential for agency ${actor.agencyId}`);const connection=await runtime.repository.upsertGoogleConnection({actor,credentialReference,scope:tokens.scope});await runtime.repository.activateGbpCapability(actor,connection.id);const discovered=await discoverGoogleResources(runtime,actor,connection.id,tokens.accessToken);await runtime.repository.completeAuthorizationSession(session.id,actor.agencyId,"completed");await runtime.credentials.revokeSecret(session.pkce_credential_ref);await runtime.repository.audit(actor,"google.authorization_completed","integration_connection",connection.id,{accounts:discovered.accounts,locations:discovered.locations});return {returnPath:session.return_path??"/?view=connections",connectionId:connection.id,...discovered};}catch(error){await runtime.repository.completeAuthorizationSession(session.id,actor.agencyId,"failed").catch(()=>undefined);await runtime.credentials.revokeSecret(session.pkce_credential_ref).catch(()=>undefined);await runtime.repository.audit(actor,"google.authorization_failed","integration_authorization_session",session.id,{error_code:sanitizeError(error)});throw error;}}
export async function discoverGoogleResources(runtime:HubRuntime,actor:ActorContext,connectionId:string,accessToken:string){try{const accounts=await runtime.google.listAccounts(accessToken);const locations=(await Promise.all(accounts.map(account=>runtime.google.listBusinessLocations(accessToken,account.name)))).flat();await runtime.repository.saveResources(actor,connectionId,[...accounts.map(account=>({capability:"google_business_profile",resourceType:"google_business_account",externalKey:account.name,displayName:account.accountName,metadata:{type:account.type,role:account.role}})),...locations.map(location=>({capability:"google_business_profile",resourceType:"google_business_location",externalKey:location.name,displayName:location.title,parentKey:location.accountName,metadata:{address:location.address,phone:location.phone,website:location.website,primary_category:location.primaryCategory,regular_hours:location.regularHours,source:"google_business_profile",...location.metadata}}))]);await runtime.repository.markSync(actor,connectionId,"success");await runtime.repository.audit(actor,"google.discovery_completed","integration_connection",connectionId,{accounts:accounts.length,locations:locations.length});return {accounts:accounts.length,locations:locations.length};}catch(error){await runtime.repository.markSync(actor,connectionId,"error",sanitizeError(error)).catch(()=>undefined);await runtime.repository.audit(actor,"google.sync_failed","integration_connection",connectionId,{error_code:sanitizeError(error)});throw error;}}
export async function getValidGoogleCredential(runtime:HubRuntime,actor:ActorContext,connection:{id:string;credential_ref:string}){const raw=await runtime.credentials.getSecret(connection.credential_ref),credential=JSON.parse(raw) as StoredGoogleCredential;if(credential.expiresAt>Date.now()+60_000)return credential;try{const refreshed=await runtime.google.refreshAuthorization(credential.refreshToken);const next={...credential,...refreshed,refreshToken:refreshed.refreshToken??credential.refreshToken};await runtime.credentials.rotateSecret(connection.credential_ref,JSON.stringify(next));return next;}catch(error){await runtime.repository.markSync(actor,connection.id,"error",error instanceof GoogleProviderError&&error.reconnect?"authorization_revoked":"refresh_failed");throw error;}}
export async function checkGoogleConnectionHealth(runtime:HubRuntime,actor:ActorContext,connectionId?:string){if(getGoogleProviderAvailability()!=="ready_for_oauth")return {status:"provider_pending" as const};const connection=await runtime.repository.googleConnection(actor,connectionId);if(!connection)return {status:"disconnected" as const};try{const credential=await getValidGoogleCredential(runtime,actor,connection),health=await runtime.google.healthCheck(credential.accessToken);if(health.status==="connected")await runtime.repository.markSync(actor,connection.id,"success");else await runtime.repository.markSync(actor,connection.id,"error",health.code);return {connection_id:connection.id,...health};}catch(error){const code=sanitizeError(error);return {connection_id:connection.id,status:code==="invalid_grant"||code==="authorization_revoked"?"attention" as const:"error" as const,code};}}
export function sanitizeError(error:unknown){if(error instanceof GoogleProviderError)return error.code;if(error instanceof Error&&["authorization_session_invalid","refresh_token_missing","actor_forbidden"].includes(error.message))return error.message;return "internal_error";}
