// @ts-expect-error Bun's test types are runtime-provided and not part of the app tsconfig.
import {describe,expect,mock,test} from "bun:test";
import {createOAuthProof,hashOAuthState,isAuthorizationSessionValid,safeReturnPath} from "../lib/connection-hub/oauth-security";
mock.module("server-only",()=>({}));
const {GoogleProviderAdapter,GOOGLE_BUSINESS_SCOPE}=await import("../lib/connection-hub/google-adapter");
const config={clientId:"client.test",clientSecret:"server-only",redirectUri:"http://localhost:5173/api/connections/google/callback"};
describe("Google provider OAuth",()=>{
 test("gera state e PKCE sem expor o secret",()=>{const proof=createOAuthProof(),url=new GoogleProviderAdapter(config,async()=>new Response()).createAuthorizationUrl({state:proof.state,codeChallenge:proof.challenge});expect(hashOAuthState(proof.state)).toBe(proof.stateHash);expect(url).toContain(encodeURIComponent(GOOGLE_BUSINESS_SCOPE));expect(url).toContain("code_challenge_method=S256");expect(url).not.toContain(config.clientSecret)});
 test("rejeita sessão expirada, usada ou de outro ator",()=>{const base={status:"pending",expires_at:new Date(Date.now()+60_000).toISOString(),initiated_by_actor_id:"actor-a"};expect(isAuthorizationSessionValid(base,"actor-a")).toBe(true);expect(isAuthorizationSessionValid({...base,expires_at:new Date(0).toISOString()},"actor-a")).toBe(false);expect(isAuthorizationSessionValid({...base,status:"completed"},"actor-a")).toBe(false);expect(isAuthorizationSessionValid(base,"actor-b")).toBe(false)});
 test("bloqueia return path externo",()=>{expect(safeReturnPath("https://evil.example")).toBe("/?view=connections");expect(safeReturnPath("//evil.example")).toBe("/?view=connections")});
 test("descobre accounts e locations com fixture read-only",async()=>{const calls:string[]=[];const mock=async(input:string|URL|Request)=>{const url=String(input);calls.push(url);if(url.includes("accountmanagement"))return Response.json({accounts:[{name:"accounts/123",accountName:"Conta Alastre",type:"ORGANIZATION"}]});return Response.json({locations:[{name:"locations/456",title:"Bionippon",storefrontAddress:{addressLines:["Rua Teste, 10"],locality:"São Paulo"},categories:{primaryCategory:{displayName:"Loja"}}}]})};const adapter=new GoogleProviderAdapter(config,mock as typeof fetch),accounts=await adapter.listAccounts("access-token"),locations=await adapter.listBusinessLocations("access-token",accounts[0].name);expect(accounts[0].accountName).toBe("Conta Alastre");expect(locations[0]).toMatchObject({title:"Bionippon",accountName:"accounts/123",primaryCategory:"Loja"});expect(calls.every(call=>call.startsWith("https://"))).toBe(true)});
 test("traduz refresh revogado para reconexão",async()=>{const adapter=new GoogleProviderAdapter(config,async()=>Response.json({error:"invalid_grant"},{status:400}));await expect(adapter.refreshAuthorization("revoked")).rejects.toMatchObject({code:"invalid_grant",reconnect:true})});
});
