"use client";

import { useEffect, useRef, useState } from "react";
import { Bot, CheckCircle2, History, MapPinned, Mic, Plus, Search, Send, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import type { ClientSummary } from "./clients-module";

type Message={id?:string;role:"user"|"assistant";content:string;input_mode?:string};
type RecognitionEvent={results:{[index:number]:{[index:number]:{transcript:string}}}};
type Recognition={lang:string;interimResults:boolean;continuous:boolean;onresult:(event:RecognitionEvent)=>void;onerror:()=>void;onend:()=>void;start:()=>void};

const trafficQuick=["Quero uma campanha para gerar novos leads", "Analise a oportunidade para mídia paga", "Crie uma campanha de marca para esta cidade"];
const seoQuick=["Analise o posicionamento local", "Crie um plano de 30 e 90 dias", "Quais palavras-chave devemos priorizar?"];
export function AgentWorkspace({clientId,onOpenBuilder}:{clientId:string;onOpenBuilder:(id:string)=>void}){
 const [clients,setClients]=useState<ClientSummary[]>([]);const [selected,setSelected]=useState(clientId);const [agentType,setAgentType]=useState<"google_ads"|"seo_local">("google_ads");const [messages,setMessages]=useState<Message[]>([]);const [text,setText]=useState("");const [sending,setSending]=useState(false);const [listening,setListening]=useState(false);const [engine,setEngine]=useState<"waiting"|"openai"|"fallback">("waiting");const [threads,setThreads]=useState<Record<string,string>>({});const bottom=useRef<HTMLDivElement>(null);
 useEffect(()=>{void fetch("/api/platform",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"clients"})}).then(r=>r.json()).then(setClients)},[]);
 useEffect(()=>{const threadKey=`${selected}:${agentType}`;void fetch("/api/platform",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"conversation",client_id:selected,agent_type:agentType})}).then(async r=>r.ok?await r.json():{thread:null,messages:[]}).then(data=>{setMessages(data.messages??[]);if(data.thread?.id)setThreads(current=>({...current,[threadKey]:data.thread.id}))})},[selected,agentType]);
 useEffect(()=>bottom.current?.scrollIntoView({behavior:"smooth"}),[messages]);
 async function send(value=text,input_mode="text"){const clean=value.trim();if(!clean||sending)return;setText("");setMessages(m=>[...m,{role:"user",content:clean,input_mode}]);setSending(true);const threadKey=`${selected}:${agentType}`;const r=await fetch("/api/platform",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"chat",agent_type:agentType,client_id:selected,thread_id:threads[threadKey],message:clean,input_mode})});if(r.ok){const d=await r.json();setEngine(d.provider==="openai"?"openai":"fallback");setThreads(current=>({...current,[threadKey]:d.thread_id}));setMessages(m=>[...m,{role:"assistant",content:d.message}])}else setMessages(m=>[...m,{role:"assistant",content:"Não consegui registrar a conversa agora. Tente novamente."}]);setSending(false)}
 function dictate(){const w=window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};const C=w.SpeechRecognition??w.webkitSpeechRecognition;if(!C){setMessages(m=>[...m,{role:"assistant",content:"O ditado não está disponível neste navegador. Você pode continuar digitando normalmente."}]);return}const r=new C();r.lang="pt-BR";r.interimResults=false;r.continuous=false;r.onresult=e=>{const spoken=e.results[0][0].transcript;setText(spoken);void send(spoken,"voice")};r.onerror=()=>setListening(false);r.onend=()=>setListening(false);setListening(true);r.start()}
 function changeClient(value:string){setSelected(value);setMessages([]);setText("");setEngine("waiting")}
 function changeAgent(value:"google_ads"|"seo_local"){setAgentType(value);setMessages([]);setText("");setEngine("waiting")}
 function newConversation(){const threadKey=`${selected}:${agentType}`;setThreads(current=>{const next={...current};delete next[threadKey];return next});setMessages([]);setText("")}
 const quick=agentType==="seo_local"?seoQuick:trafficQuick;
 return <div className="agent-page"><div className="module-title"><div><div className="eyebrow"><Bot/> AGENTES ESPECIALIZADOS</div><h1>{agentType==="seo_local"?"Especialista em SEO Local":"Gestor de Tráfego"}</h1><p>Converse por texto ou voz. O agente consulta o DNA e mantém o contexto separado para cada cliente.</p></div><select value={selected} onChange={e=>changeClient(e.target.value)}>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>
 <div className="agent-selector"><button type="button" className={agentType==="google_ads"?"active":""} onClick={()=>changeAgent("google_ads")}><Search/> Gestor de Tráfego<span>Google Ads e performance</span></button><button type="button" className={agentType==="seo_local"?"active":""} onClick={()=>changeAgent("seo_local")}><MapPinned/> SEO Local<span>Google, Maps e Local Pack</span></button></div>
 <div className="agent-mode"><Sparkles/><div><strong>{engine==="openai"?"AI Gateway conectado":engine==="fallback"?"Fallback seguro ativo":"AI Gateway preparado"}</strong><span>{engine==="openai"?"Resposta gerada com DNA e memória · uso registrado em Custos":engine==="fallback"?"O provedor não foi usado; a resposta por regras manteve o fluxo disponível":"O sistema verifica chave, limite mensal e custo antes de cada chamada"}</span></div><Badge variant="outline">{engine==="openai"?"IA REAL":"SEM PUBLICAÇÃO"}</Badge></div>
 <section className="agent-layout"><article className="chat-panel"><div className="chat-head"><span className="agent-avatar">{agentType==="seo_local"?<MapPinned/>:<Bot/>}</span><div><strong>{agentType==="seo_local"?"Agente de Inteligência Local":"Agente de Performance"}</strong><span><i/> Online para planejamento · histórico recuperado</span></div><Button variant="outline" size="sm" onClick={newConversation}><Plus/> Nova conversa</Button></div><div className="messages">{messages.length===0&&<div className="message assistant"><span><Bot/></span><p>{agentType==="seo_local"?"Agente de SEO Local ativado. Vou analisar Perfil da Empresa, Maps, Local Pack e presença orgânica usando o DNA salvo.":"Olá. Descreva a ideia da campanha. Vou usar o DNA salvo para organizar estratégia, perguntas e um rascunho controlado."}</p></div>}{messages.map((m,i)=><div key={m.id??`${m.role}-${i}`} className={`message ${m.role}`}><span>{m.role==="assistant"?<Bot/>:<UserRound/>}</span><p>{m.content}</p></div>)}{sending&&<div className="message assistant"><span><Bot/></span><p>Analisando o DNA e registrando o contexto...</p></div>}<div ref={bottom}/></div>
 <div className="quick-prompts">{quick.map(q=><button key={q} onClick={()=>void send(q)}>{q}</button>)}</div><div className="composer"><Button variant="outline" className={listening?"listening":""} onClick={dictate} title="Falar"><Mic/></Button><Textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send()}}} placeholder="Ex.: Quero gerar leads para imóveis no bairro X em Santo André..."/><Button onClick={()=>void send()} disabled={sending||!text.trim()}><Send/></Button></div><small className="composer-help">Enter envia · Shift + Enter quebra a linha · o áudio é transformado em texto pelo navegador</small></article>
 <aside className="agent-context"><div><span className="section-kicker">CONTEXTO ATIVO</span><h2>{clients.find(c=>c.id===selected)?.name??"Cliente"}</h2></div><ul><li><CheckCircle2/> DNA e memória conectados</li><li><History/> Última conversa recuperada</li><li><CheckCircle2/> {agentType==="seo_local"?"Método DOMÍNIO LOCAL ativo":"Regras de mídia aplicadas"}</li><li><ShieldCheck/> Escrita externa bloqueada</li></ul><div className="context-flow"><span>Conversa</span><b>→</b><span>{agentType==="seo_local"?"Plano":"Rascunho"}</span><b>→</b><span>Aprovação</span></div>{agentType==="google_ads"&&<Button onClick={()=>onOpenBuilder(selected)}>Abrir criador de campanha</Button>}</aside></section>
 </div>;
}
