"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Bot, CheckCircle2, History, MapPinned, Mic, Plus, Search, Send, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { DecisionState, IntegrationState } from "@/components/platform-state";
import { isArrayOf, isRecord, isRequestCancelled, isString, postPlatform } from "@/lib/platform-api";
import { isClientSummaryArray, type ClientSummary } from "./clients-module";

type Message={id?:string;role:"user"|"assistant";content:string;input_mode?:string};
type RecognitionEvent={results:{[index:number]:{[index:number]:{transcript:string}}}};
type Recognition={lang:string;interimResults:boolean;continuous:boolean;onresult:(event:RecognitionEvent)=>void;onerror:()=>void;onend:()=>void;start:()=>void};

const trafficQuick=["Quero uma campanha para gerar novos leads", "Analise a oportunidade para mídia paga", "Crie uma campanha de marca para esta cidade"];
const seoQuick=["Organize as oportunidades com os dados disponíveis", "Prepare uma ideia de postagem usando apenas o DNA", "Quais dados ainda faltam para analisar o SEO Local?"];
const isMessage=(value:unknown):value is Message=>isRecord(value)&&(value.role==="user"||value.role==="assistant")&&isString(value.content);
const isConversation=(value:unknown):value is {thread:{id:string}|null;messages:Message[]}=>isRecord(value)&&(value.thread===null||(isRecord(value.thread)&&isString(value.thread.id)))&&isArrayOf(isMessage)(value.messages);
const isChatResponse=(value:unknown):value is {provider:string;thread_id:string;message:string}=>isRecord(value)&&isString(value.provider)&&isString(value.thread_id)&&isString(value.message);
export function AgentWorkspace({clientId,onOpenBuilder,onOpenClients}:{clientId:string;onOpenBuilder:(id:string)=>void;onOpenClients?:()=>void}){
 const [clients,setClients]=useState<ClientSummary[]>([]);const [selected,setSelected]=useState(clientId);const [loading,setLoading]=useState(true);const [unavailable,setUnavailable]=useState(false);const [agentType,setAgentType]=useState<"google_ads"|"seo_local">("seo_local");const [messages,setMessages]=useState<Message[]>([]);const [text,setText]=useState("");const [sending,setSending]=useState(false);const [listening,setListening]=useState(false);const [engine,setEngine]=useState<"waiting"|"openai"|"fallback">("waiting");const [threads,setThreads]=useState<Record<string,string>>({});const bottom=useRef<HTMLDivElement>(null);
 const loadClients=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setUnavailable(false);try{const list=await postPlatform({action:"clients"},isClientSummaryArray,signal);if(signal?.aborted)return;setClients(list);setSelected(current=>list.some(client=>client.id===current)?current:list[0]?.id??"")}catch(error){if(isRequestCancelled(error))return;setClients([]);setSelected("");setUnavailable(true)}finally{if(!signal?.aborted)setLoading(false)}},[]);
 useEffect(()=>{const controller=new AbortController();const timer=window.setTimeout(()=>void loadClients(controller.signal),0);return()=>{window.clearTimeout(timer);controller.abort()}},[loadClients]);
 useEffect(()=>{if(!selected||!clients.some(client=>client.id===selected))return;const controller=new AbortController();const threadKey=`${selected}:${agentType}`;void postPlatform({action:"conversation",client_id:selected,agent_type:agentType},isConversation,controller.signal).then(data=>{if(controller.signal.aborted)return;setMessages(data.messages);if(data.thread?.id)setThreads(current=>({...current,[threadKey]:data.thread!.id}))}).catch(error=>{if(!isRequestCancelled(error)){setMessages([]);setUnavailable(true)}});return()=>{controller.abort()}},[clients,selected,agentType]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth"})},[messages]);
 async function send(value=text,input_mode="text"){const clean=value.trim();if(!clean||sending||!selected)return;setText("");setMessages(m=>[...m,{role:"user",content:clean,input_mode}]);setSending(true);const threadKey=`${selected}:${agentType}`;try{const data=await postPlatform({action:"chat",agent_type:agentType,client_id:selected,thread_id:threads[threadKey],message:clean,input_mode},isChatResponse);setEngine(data.provider==="openai"?"openai":"fallback");setThreads(current=>({...current,[threadKey]:data.thread_id}));setMessages(m=>[...m,{role:"assistant",content:data.message}])}catch{setMessages(m=>[...m,{role:"assistant",content:"A integração ainda não está conectada. Sua mensagem não foi enviada; tente novamente mais tarde."}]);setUnavailable(true)}finally{setSending(false)}}
 function dictate(){const w=window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};const C=w.SpeechRecognition??w.webkitSpeechRecognition;if(!C){setMessages(m=>[...m,{role:"assistant",content:"O ditado não está disponível neste navegador. Você pode continuar digitando normalmente."}]);return}const r=new C();r.lang="pt-BR";r.interimResults=false;r.continuous=false;r.onresult=e=>{const spoken=e.results[0][0].transcript;setText(spoken);void send(spoken,"voice")};r.onerror=()=>setListening(false);r.onend=()=>setListening(false);setListening(true);r.start()}
 function changeClient(value:string){setSelected(value);setMessages([]);setText("");setEngine("waiting")}
 function changeAgent(value:"google_ads"|"seo_local"){setAgentType(value);setMessages([]);setText("");setEngine("waiting")}
 function newConversation(){const threadKey=`${selected}:${agentType}`;setThreads(current=>{const next={...current};delete next[threadKey];return next});setMessages([]);setText("")}
 const quick=agentType==="seo_local"?seoQuick:trafficQuick;
 const hasClient=Boolean(selected&&clients.some(client=>client.id===selected));
 return <div className="agent-page"><div className="module-title"><div><div className="eyebrow"><Bot/> AGENTES ESPECIALIZADOS</div><h1>Em que a Alastre pode ajudar agora?</h1><p>Escolha uma especialidade, selecione o cliente e comece uma conversa.</p></div>{clients.length>0?<select value={selected} onChange={e=>changeClient(e.target.value)}>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>:null}</div>
 {unavailable?<IntegrationState compact message="As conversas ficam disponíveis quando os serviços deste ambiente são conectados." onRetry={()=>void loadClients()}/>:loading?<DecisionState title="Preparando agentes" message="Estamos carregando clientes e conversas."/>:!hasClient?<DecisionState icon={Bot} title="Adicione um cliente para começar uma conversa." message="O agente usa o DNA do cliente para manter respostas e planos no contexto certo." actionLabel={onOpenClients?"Adicionar cliente":undefined} onAction={onOpenClients}/>:null}
 <div className="agent-selector"><button type="button" className={agentType==="google_ads"?"active":""} onClick={()=>changeAgent("google_ads")}><Search/> Gestor de Tráfego<span>Google Ads e performance</span></button><button type="button" className={agentType==="seo_local"?"active":""} onClick={()=>changeAgent("seo_local")}><MapPinned/> SEO Local<span>Google, Maps e Local Pack</span></button></div>
 <div className="agent-mode"><Sparkles/><div><strong>{unavailable?"Integração ainda não conectada":engine==="openai"?"AI Gateway conectado":engine==="fallback"?"Fallback seguro ativo":"AI Gateway preparado"}</strong><span>{unavailable?"A interface continua disponível, mas conversas aguardam a conexão deste ambiente":engine==="openai"?"Resposta gerada com DNA e memória · uso registrado em Custos":engine==="fallback"?"O provedor não foi usado; a resposta por regras manteve o fluxo disponível":"O sistema verifica chave, limite mensal e custo antes de cada chamada"}</span></div><Badge variant="outline">{unavailable?"INDISPONÍVEL":engine==="openai"?"IA REAL":"SEM PUBLICAÇÃO"}</Badge></div>
 <section className="agent-layout"><article className="chat-panel"><div className="chat-head"><span className="agent-avatar">{agentType==="seo_local"?<MapPinned/>:<Bot/>}</span><div><strong>{agentType==="seo_local"?"Agente de Inteligência Local":"Agente de Performance"}</strong><span>{unavailable?"Aguardando conexão para recuperar o histórico":<><i/> Online para planejamento · histórico recuperado</>}</span></div><Button variant="outline" size="sm" onClick={newConversation} disabled={!hasClient}><Plus/> Nova conversa</Button></div><div className="messages">{messages.length===0&&<div className="message assistant"><span><Bot/></span><p>{unavailable?"A integração ainda não está conectada. Você pode revisar esta tela e voltar quando o ambiente estiver disponível.":agentType==="seo_local"?"Agente de SEO Local ativado. Vou analisar Perfil da Empresa, Maps, Local Pack e presença orgânica usando o DNA salvo.":"Olá. Descreva a ideia da campanha. Vou usar o DNA salvo para organizar estratégia, perguntas e um rascunho controlado."}</p></div>}{messages.map((m,i)=><div key={m.id??`${m.role}-${i}`} className={`message ${m.role}`}><span>{m.role==="assistant"?<Bot/>:<UserRound/>}</span><p>{m.content}</p></div>)}{sending&&<div className="message assistant"><span><Bot/></span><p>Analisando o DNA e registrando o contexto...</p></div>}<div ref={bottom}/></div>
 <div className="quick-prompts">{quick.map(q=><button key={q} onClick={()=>void send(q)} disabled={!hasClient||sending}>{q}</button>)}</div><div className="composer"><Button variant="outline" className={listening?"listening":""} onClick={dictate} title="Falar" aria-label="Ditado por voz" disabled={!hasClient}><Mic/></Button><Textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send()}}} placeholder={hasClient?"Ex.: Quero gerar leads para imóveis no bairro X em Santo André...":"Selecione um cliente para iniciar"} disabled={!hasClient}/><Button onClick={()=>void send()} disabled={sending||!text.trim()||!hasClient} aria-label="Enviar mensagem"><Send/></Button></div><small className="composer-help">Enter envia · Shift + Enter quebra a linha · o áudio é transformado em texto pelo navegador</small></article>
 <aside className="agent-context"><div><span className="section-kicker">CONTEXTO ATIVO</span><h2>{clients.find(c=>c.id===selected)?.name??"Nenhum cliente"}</h2></div>{clients.find(c=>c.id===selected)?.dna?.status!=="confirmed"&&<div style={{margin:"10px 0",padding:"8px 12px",background:"color-mix(in srgb,var(--warning) 12%,var(--surface-1))",border:"1px solid color-mix(in srgb,var(--warning) 30%,var(--line))",borderRadius:"10px",fontSize:".8125rem",color:"var(--content-primary)"}}><strong>⚠️ DNA em Homologação</strong><p style={{margin:"4px 0 0",fontSize:".75rem",color:"var(--content-secondary)"}}>O DNA deste cliente ainda não foi confirmado por um operador. As respostas do agente devem ser conferidas antes de aprovar ações.</p></div>}<ul><li><CheckCircle2/> DNA e memória do cliente</li><li><History/> Histórico quando disponível</li><li><CheckCircle2/> {agentType==="seo_local"?"Perfil, avaliações, conteúdo e score preparados":"Regras de mídia aplicadas"}</li><li><ShieldCheck/> Escrita externa bloqueada</li></ul>{agentType==="seo_local"&&unavailable?<p className="agent-missing-data">Dado necessário ainda não disponível.</p>:null}<div className="context-flow"><span>Conversa</span><b>→</b><span>{agentType==="seo_local"?"Plano":"Rascunho"}</span><b>→</b><span>Aprovação</span></div>{agentType==="google_ads"&&<Button onClick={()=>onOpenBuilder(selected)} disabled={!hasClient}>Abrir criador de campanha</Button>}</aside></section>
 </div>;
}
