"use client";

import { useEffect, useState } from "react";
import { BrainCircuit, CheckCircle2, Database, ExternalLink, Fingerprint, MapPin, RotateCcw, ShieldCheck, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { ClientSummary } from "./clients-module";

type Workspace={client:ClientSummary;dna:{status:string;version:number;business_data:Record<string,unknown>;local_intelligence:Record<string,unknown>;paid_media_rules:Record<string,unknown>};sources:Array<{id:string;source_type:string;label:string;status:string;source_url:string|null}>};
const pretty=(v:unknown)=>Array.isArray(v)?v.join(" · "):typeof v==="string"?v:typeof v==="number"?String(v):"—";
export function DnaModule({clientId,onOpenAgent}:{clientId:string;onOpenAgent:(id:string)=>void}){const [data,setData]=useState<Workspace|null>(null);const [clients,setClients]=useState<ClientSummary[]>([]);const [selected,setSelected]=useState(clientId);
 const [deciding,setDeciding]=useState(false);const [notice,setNotice]=useState("");
 useEffect(()=>{void fetch("/api/platform",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"clients"})}).then(r=>r.json()).then(setClients)},[]);
 useEffect(()=>{if(!selected)return;void fetch("/api/platform",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"workspace",client_id:selected})}).then(r=>r.json()).then(setData)},[selected]);
 async function setDnaStatus(status:"confirmed"|"needs_review"){setDeciding(true);setNotice("");const r=await fetch("/api/platform",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"dna_status",client_id:selected,status})});if(r.ok){setData(current=>current?{...current,dna:{...current.dna,status}}:current);setNotice(status==="confirmed"?"DNA confirmado e registrado na auditoria.":"DNA devolvido para revisão.")}else setNotice("Não foi possível atualizar o DNA.");setDeciding(false)}
 const diagnosis=data?.dna.local_intelligence.diagnosis as {score?:number;status?:string;strengths?:string[];priorities?:string[];method?:string}|undefined;
 return <div className="dna-page"><div className="module-title"><div><div className="eyebrow"><Fingerprint/> MEMÓRIA DO CLIENTE</div><h1>DNA e inteligência local</h1><p>Fatos confirmados, fontes e regras que acompanham o cliente em todos os agentes.</p></div><select value={selected} onChange={e=>setSelected(e.target.value)}>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>
 {!data?<div className="empty-state">Carregando DNA...</div>:<><section className="dna-hero"><div><Badge><CheckCircle2/> {data.dna.status==="confirmed"?"Confirmado":data.dna.status==="needs_review"?"Revisão solicitada":"Aguardando confirmação"}</Badge><h2>{data.client.name}</h2><p>Versão {data.dna.version} · memória central persistida no Supabase</p></div><span className="dna-score"><strong>{Math.min(98,70+data.sources.length*7)}%</strong><small>base preenchida</small></span></section>
 <section className="dna-grid"><article className="panel"><div className="panel-heading"><div><span className="section-kicker">NEGÓCIO</span><h2>Identidade operacional</h2></div><Database/></div><dl className="data-list"><div><dt>Segmento</dt><dd>{pretty(data.dna.business_data.segment)}</dd></div><div><dt>Cidade(s)</dt><dd>{pretty(data.dna.business_data.cities??data.dna.business_data.city)}</dd></div><div><dt>Serviço principal</dt><dd>{pretty(data.dna.business_data.primary_service)}</dd></div><div><dt>Objetivo</dt><dd>{pretty(data.dna.business_data.objective)}</dd></div></dl></article>
 <article className="panel"><div className="panel-heading"><div><span className="section-kicker">INTELIGÊNCIA LOCAL</span><h2>Posicionamento</h2></div><MapPin/></div><dl className="data-list">{Object.entries(data.dna.local_intelligence).slice(0,5).map(([k,v])=><div key={k}><dt>{k.replaceAll("_"," ")}</dt><dd>{pretty(v)}</dd></div>)}</dl></article>
 <article className="panel"><div className="panel-heading"><div><span className="section-kicker">MÍDIA PAGA</span><h2>Guardrails</h2></div><ShieldCheck/></div><dl className="data-list">{Object.entries(data.dna.paid_media_rules).slice(0,6).map(([k,v])=><div key={k}><dt>{k.replaceAll("_"," ")}</dt><dd>{pretty(v)}</dd></div>)}</dl></article></section>
 {diagnosis&&<section className="seo-diagnosis"><div className="diagnosis-score"><Sparkles/><strong>{diagnosis.score??"—"}%</strong><span>Score inicial</span><small>{diagnosis.method}</small></div><article><span className="section-kicker">PONTOS FORTES</span><ul>{diagnosis.strengths?.map(item=><li key={item}><CheckCircle2/>{item}</li>)}</ul></article><article><span className="section-kicker">PRIORIDADES</span><ol>{diagnosis.priorities?.map((item,index)=><li key={item}><b>{index+1}</b>{item}</li>)}</ol></article></section>}
 <section className="panel sources-panel"><div className="panel-heading"><div><span className="section-kicker">PROVENIÊNCIA</span><h2>Fontes do conhecimento</h2></div><Badge variant="outline">{data.sources.length} fontes</Badge></div>{data.sources.map(s=><div className="source-row" key={s.id}><span className="source-icon"><ExternalLink/></span><div><strong>{s.label}</strong><small>{s.source_type.replaceAll("_"," ")}</small></div><Badge variant="outline" className={`source-${s.status}`}>{s.status==="imported"?"Importada":"Revisar"}</Badge></div>)}</section>
 <section className="dna-decision"><div><ShieldCheck/><span><strong>Revisão humana do DNA</strong><small>Confirme somente depois de conferir os dados e fontes. A decisão ficará registrada.</small></span></div><div>{notice&&<small className="dna-notice">{notice}</small>}{data.dna.status==="confirmed"?<Button variant="outline" onClick={()=>void setDnaStatus("needs_review")} disabled={deciding}><RotateCcw/> Solicitar revisão</Button>:<Button onClick={()=>void setDnaStatus("confirmed")} disabled={deciding}><CheckCircle2/> Confirmar DNA</Button>}<Button variant="outline" onClick={()=>onOpenAgent(selected)}><BrainCircuit/> Conversar usando este DNA</Button></div></section></>}</div>}
