"use client";

import { useCallback, useEffect, useState } from "react";
import { BrainCircuit, CheckCircle2, Database, ExternalLink, Fingerprint, MapPin, RotateCcw, ShieldCheck, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { IntegrationState } from "@/components/platform-state";
import { isArrayOf, isRecord, isRequestCancelled, isString, postPlatform } from "@/lib/platform-api";
import { isClientSummaryArray, type ClientSummary } from "./clients-module";

type Workspace={client:ClientSummary;dna:{status:string;version:number;business_data:Record<string,unknown>;local_intelligence:Record<string,unknown>;paid_media_rules:Record<string,unknown>};sources:Array<{id:string;source_type:string;label:string;status:string;source_url:string|null}>};
const pretty=(v:unknown)=>Array.isArray(v)?v.join(" · "):typeof v==="string"?v:typeof v==="number"?String(v):"—";
const isSource=(value:unknown):value is Workspace["sources"][number]=>isRecord(value)&&isString(value.id)&&isString(value.source_type)&&isString(value.label)&&isString(value.status)&&(value.source_url===null||isString(value.source_url));
const isWorkspace=(value:unknown):value is Workspace=>isRecord(value)&&isRecord(value.client)&&isString(value.client.id)&&isString(value.client.name)&&isRecord(value.dna)&&isString(value.dna.status)&&typeof value.dna.version==="number"&&isRecord(value.dna.business_data)&&isRecord(value.dna.local_intelligence)&&isRecord(value.dna.paid_media_rules)&&isArrayOf(isSource)(value.sources);
export function DnaModule({clientId,onOpenAgent}:{clientId:string;onOpenAgent:(id:string)=>void}){const [data,setData]=useState<Workspace|null>(null);const [clients,setClients]=useState<ClientSummary[]>([]);const [selected,setSelected]=useState(clientId);
 const [loading,setLoading]=useState(true);const [unavailable,setUnavailable]=useState(false);const [deciding,setDeciding]=useState(false);const [notice,setNotice]=useState("");
 const loadClients=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setUnavailable(false);setData(null);try{const list=await postPlatform({action:"clients"},isClientSummaryArray,signal);if(signal?.aborted)return;setClients(list);setSelected(current=>list.some(client=>client.id===current)?current:list[0]?.id??"");if(list.length===0)setLoading(false)}catch(error){if(isRequestCancelled(error))return;setClients([]);setSelected("");setUnavailable(true);setLoading(false)}},[]);
 useEffect(()=>{const controller=new AbortController();const timer=window.setTimeout(()=>void loadClients(controller.signal),0);return()=>{window.clearTimeout(timer);controller.abort()}},[loadClients]);
 useEffect(()=>{if(!selected||!clients.some(client=>client.id===selected))return;const controller=new AbortController();const timer=window.setTimeout(()=>{setLoading(true);setData(null);void postPlatform({action:"workspace",client_id:selected},isWorkspace,controller.signal).then(workspace=>{if(!controller.signal.aborted){setData(workspace);setUnavailable(false)}}).catch(error=>{if(!isRequestCancelled(error)){setData(null);setUnavailable(true)}}).finally(()=>{if(!controller.signal.aborted)setLoading(false)})},0);return()=>{window.clearTimeout(timer);controller.abort()}},[clients,selected]);
 async function setDnaStatus(status:"confirmed"|"needs_review"){setDeciding(true);setNotice("");try{await postPlatform({action:"dna_status",client_id:selected,status},isRecord);setData(current=>current?{...current,dna:{...current.dna,status}}:current);setNotice(status==="confirmed"?"DNA confirmado e registrado na auditoria.":"DNA devolvido para revisão.")}catch{setNotice("Não foi possível atualizar o DNA agora.")}finally{setDeciding(false)}}
 const diagnosis=data?.dna.local_intelligence.diagnosis as {score?:number;status?:string;strengths?:string[];priorities?:string[];method?:string}|undefined;
 return <div className="dna-page"><div className="module-title"><div><div className="eyebrow"><Fingerprint/> MEMÓRIA DO CLIENTE</div><h1>DNA e inteligência local</h1><p>Fatos confirmados, fontes e regras que acompanham o cliente em todos os agentes.</p></div><select value={selected} onChange={e=>setSelected(e.target.value)} disabled={clients.length===0}>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>
 {unavailable?<IntegrationState message="O DNA será exibido quando a conexão da plataforma estiver disponível. Nenhuma memória foi alterada." onRetry={()=>void loadClients()}/>:loading?<div className="empty-state">Carregando DNA...</div>:clients.length===0?<div className="empty-state">Cadastre um cliente para começar a construir o DNA.</div>:!data?<div className="empty-state">Não foi possível localizar o DNA deste cliente.</div>:<><section className="dna-hero"><div><Badge><CheckCircle2/> {data.dna.status==="confirmed"?"Confirmado":data.dna.status==="needs_review"?"Revisão solicitada":"Aguardando confirmação"}</Badge><h2>{data.client.name}</h2><p>Versão {data.dna.version} · memória central persistida no Supabase</p></div><span className="dna-score"><strong>{Math.min(98,70+data.sources.length*7)}%</strong><small>base preenchida</small></span></section>
 <section className="dna-grid"><article className="panel"><div className="panel-heading"><div><span className="section-kicker">NEGÓCIO</span><h2>Identidade operacional</h2></div><Database/></div><dl className="data-list"><div><dt>Segmento</dt><dd>{pretty(data.dna.business_data.segment)}</dd></div><div><dt>Cidade(s)</dt><dd>{pretty(data.dna.business_data.cities??data.dna.business_data.city)}</dd></div><div><dt>Serviço principal</dt><dd>{pretty(data.dna.business_data.primary_service)}</dd></div><div><dt>Objetivo</dt><dd>{pretty(data.dna.business_data.objective)}</dd></div></dl></article>
 <article className="panel"><div className="panel-heading"><div><span className="section-kicker">INTELIGÊNCIA LOCAL</span><h2>Posicionamento</h2></div><MapPin/></div><dl className="data-list">{Object.entries(data.dna.local_intelligence).slice(0,5).map(([k,v])=><div key={k}><dt>{k.replaceAll("_"," ")}</dt><dd>{pretty(v)}</dd></div>)}</dl></article>
 <article className="panel"><div className="panel-heading"><div><span className="section-kicker">MÍDIA PAGA</span><h2>Guardrails</h2></div><ShieldCheck/></div><dl className="data-list">{Object.entries(data.dna.paid_media_rules).slice(0,6).map(([k,v])=><div key={k}><dt>{k.replaceAll("_"," ")}</dt><dd>{pretty(v)}</dd></div>)}</dl></article></section>
 {diagnosis&&<section className="seo-diagnosis"><div className="diagnosis-score"><Sparkles/><strong>{diagnosis.score??"—"}%</strong><span>Score inicial</span><small>{diagnosis.method}</small></div><article><span className="section-kicker">PONTOS FORTES</span><ul>{diagnosis.strengths?.map(item=><li key={item}><CheckCircle2/>{item}</li>)}</ul></article><article><span className="section-kicker">PRIORIDADES</span><ol>{diagnosis.priorities?.map((item,index)=><li key={item}><b>{index+1}</b>{item}</li>)}</ol></article></section>}
 <section className="panel sources-panel"><div className="panel-heading"><div><span className="section-kicker">PROVENIÊNCIA</span><h2>Fontes do conhecimento</h2></div><Badge variant="outline">{data.sources.length} fontes</Badge></div>{data.sources.map(s=><div className="source-row" key={s.id}><span className="source-icon"><ExternalLink/></span><div><strong>{s.label}</strong><small>{s.source_type.replaceAll("_"," ")}</small></div><Badge variant="outline" className={`source-${s.status}`}>{s.status==="imported"?"Importada":"Revisar"}</Badge></div>)}</section>
 <section className="dna-decision"><div><ShieldCheck/><span><strong>Revisão humana do DNA</strong><small>Confirme somente depois de conferir os dados e fontes. A decisão ficará registrada.</small></span></div><div>{notice&&<small className="dna-notice">{notice}</small>}{data.dna.status==="confirmed"?<Button variant="outline" onClick={()=>void setDnaStatus("needs_review")} disabled={deciding}><RotateCcw/> Solicitar revisão</Button>:<Button onClick={()=>void setDnaStatus("confirmed")} disabled={deciding}><CheckCircle2/> Confirmar DNA</Button>}<Button variant="outline" onClick={()=>onOpenAgent(selected)}><BrainCircuit/> Conversar usando este DNA</Button></div></section></>}</div>}
