"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Activity, CheckCircle2, CircleAlert, CircleHelp, Database, FileCheck2, Globe2, Network, RefreshCw, ScanSearch, ShieldCheck, Waypoints } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { IntegrationState } from "@/components/platform-state";
import { isArrayOf, isIntegrationUnavailable, isNumber, isObject, isRecord, isRequestCancelled, isString, postPlatform, type JsonGuard } from "@/lib/platform-api";

type Client={id:string;name:string};
type Resource={id:string;resource_type:string;external_id:string;status:string;ownership:string;metadata:Record<string,unknown>};
type PlanAction={target:string;operation:string;count?:number;external_write?:boolean};
type Deployment={id:string;status:string;decision:string;created_at:string;approval_id?:string|null;plan:{actions?:PlanAction[];desired_events?:string[];safety?:{external_writes?:boolean;publish?:boolean}}&Record<string,unknown>};
type Validation={id:string;phase:string;status:string;validator:string;validated_at:string;evidence:Record<string,unknown>};
type Candidate={id:string;deployment_id:string;artifact_type:string;status:string;config_hash:string;manifest:Record<string,unknown>;created_at:string};
type ResourceCandidate={id:string;resource_type:"gtm_container"|"ga4_web_stream";external_id:string;display_name:string;match_reason:string;confidence:number;selected:boolean;metadata:Record<string,unknown>};
type ExecutionRun={id:string;deployment_id:string;status:string;config_hash:string;workspace_path?:string|null;version_path?:string|null;publish_approval_id?:string|null;published_at?:string|null;created_at:string};
type Profile={id:string;domain:string;platform:string;industry:string;template_key:string;status:string;health:string}|null;
type Workspace={client:Client;profile:Profile;resources:Resource[];resource_candidates:ResourceCandidate[];deployments:Deployment[];validations:Validation[];candidates:Candidate[];execution_runs:ExecutionRun[];external_write_mode:string};
type LoadError={title:string;message:string};
const isClient=(value:unknown):value is Client=>isRecord(value)&&isString(value.id)&&isString(value.name);
const isClients=isArrayOf(isClient);
const isResource=(value:unknown):value is Resource=>isRecord(value)&&isString(value.id)&&isString(value.resource_type)&&isString(value.external_id)&&isString(value.status)&&isString(value.ownership)&&isRecord(value.metadata);
const isResourceCandidate=(value:unknown):value is ResourceCandidate=>isRecord(value)&&isString(value.id)&&(value.resource_type==="gtm_container"||value.resource_type==="ga4_web_stream")&&isString(value.external_id)&&isString(value.display_name)&&isString(value.match_reason)&&isNumber(value.confidence)&&typeof value.selected==="boolean"&&isRecord(value.metadata);
const isDeployment=(value:unknown):value is Deployment=>isRecord(value)&&isString(value.id)&&isString(value.status)&&isString(value.decision)&&isString(value.created_at)&&isRecord(value.plan);
const isValidation=(value:unknown):value is Validation=>isRecord(value)&&isString(value.id)&&isString(value.phase)&&isString(value.status)&&isString(value.validator)&&isString(value.validated_at)&&isRecord(value.evidence);
const isCandidate=(value:unknown):value is Candidate=>isRecord(value)&&isString(value.id)&&isString(value.deployment_id)&&isString(value.artifact_type)&&isString(value.status)&&isString(value.config_hash)&&isRecord(value.manifest)&&isString(value.created_at);
const isExecutionRun=(value:unknown):value is ExecutionRun=>isRecord(value)&&isString(value.id)&&isString(value.deployment_id)&&isString(value.status)&&isString(value.config_hash)&&isString(value.created_at);
const isProfile=(value:unknown):value is Exclude<Profile,null>=>isRecord(value)&&isString(value.id)&&isString(value.domain)&&isString(value.platform)&&isString(value.industry)&&isString(value.template_key)&&isString(value.status)&&isString(value.health);
const isTrackingWorkspace=(value:unknown):value is Workspace=>isRecord(value)&&isClient(value.client)&&(value.profile===null||isProfile(value.profile))&&isArrayOf(isResource)(value.resources)&&isArrayOf(isResourceCandidate)(value.resource_candidates)&&isArrayOf(isDeployment)(value.deployments)&&isArrayOf(isValidation)(value.validations)&&isArrayOf(isCandidate)(value.candidates)&&isArrayOf(isExecutionRun)(value.execution_runs)&&isString(value.external_write_mode);
const isDiscoveryResult=(value:unknown):value is {resource_count:number;legacy_count:number}=>isRecord(value)&&isNumber(value.resource_count)&&isNumber(value.legacy_count);
const isCandidateResult=(value:unknown):value is {status:string;validation:{container_selected:boolean;ga4_selected:boolean}}=>isRecord(value)&&isString(value.status)&&isRecord(value.validation);
const isPreflightResult=(value:unknown):value is {status:string;evidence:{key_events_to_prepare:string[];workspace_name_conflict:boolean}}=>isRecord(value)&&isString(value.status)&&isRecord(value.evidence)&&Array.isArray(value.evidence.key_events_to_prepare);
const isVersionResult=(value:unknown):value is {version_path?:string}=>isRecord(value)&&(value.version_path===undefined||isString(value.version_path));
const isValidationResult=(value:unknown):value is {validation_status:string}=>isRecord(value)&&isString(value.validation_status);

const labels:Record<string,string>={gtm_container:"GTM Container",gtm_version:"Versão GTM",ga4_property:"GA4 Property",ga4_web_stream:"Web Stream",legacy_external_resource:"Recurso legado"};
const statusLabel:Record<string,string>={published:"Publicado",production_validated:"Produção validada",planned:"Plano preparado",waiting_approval:"Aguardando aprovação",approved:"Plano aprovado",failed:"Bloqueado",pending:"Pendente",passed:"Aprovado",legacy:"Somente leitura",validated:"Validado"};
const operationLabel:Record<string,string>={reuse:"Reutilizar existente",create_candidate:"Preparar criação",prepare_candidate:"Preparar configuração",observe_only:"Somente observar"};

function HelpTip({title,children}:{title:string;children:string}) {
  return <details className="help-tip"><summary aria-label={`Entenda: ${title}`}><CircleHelp/> O que é isso?</summary><div><strong>{title}</strong><p>{children}</p></div></details>;
}

export function TrackingModule({clientId,onSelectClient}:{clientId:string;onSelectClient:(id:string)=>void}) {
  const [clients,setClients]=useState<Client[]>([]); const [data,setData]=useState<Workspace|null>(null); const [loading,setLoading]=useState(true); const [working,setWorking]=useState(false); const [notice,setNotice]=useState("");
  const [loadError,setLoadError]=useState<LoadError|null>(null);
  const [domain,setDomain]=useState(""); const [platform,setPlatform]=useState("custom"); const [industry,setIndustry]=useState("local_business");
  const [gtmCandidateId,setGtmCandidateId]=useState(""); const [ga4CandidateId,setGa4CandidateId]=useState("");
  const [gtmAccount,setGtmAccount]=useState(""); const [ga4Account,setGa4Account]=useState("");
  const call=useCallback(<T,>(body:Record<string,unknown>,guard:JsonGuard<T>,signal?:AbortSignal)=>postPlatform(body,guard,signal),[]);
  const load=useCallback(async(signal?:AbortSignal)=>{setLoading(true);setLoadError(null);try{const list=await call({action:"clients"},isClients,signal);if(signal?.aborted)return;setClients(list);const selected=list.some(item=>item.id===clientId)?clientId:list[0]?.id;if(selected&&selected!==clientId)onSelectClient(selected);if(selected){const workspace=await call({action:"tracking_workspace",client_id:selected},isTrackingWorkspace,signal);if(signal?.aborted)return;setData(workspace);setDomain(workspace.profile?.domain??"");setPlatform(workspace.profile?.platform??"custom");setIndustry(workspace.profile?.industry??"local_business");const gtm=workspace.resource_candidates.filter(item=>item.resource_type==="gtm_container").sort((a,b)=>Number(b.selected)-Number(a.selected)||b.confidence-a.confidence)[0];const ga4=workspace.resource_candidates.filter(item=>item.resource_type==="ga4_web_stream").sort((a,b)=>Number(b.selected)-Number(a.selected)||b.confidence-a.confidence)[0];setGtmCandidateId(gtm?.id??"");setGa4CandidateId(ga4?.id??"")}else{setData(null)}}catch(error){if(isRequestCancelled(error))return;setClients([]);setData(null);setLoadError(isIntegrationUnavailable(error)?{title:"Integração ainda não conectada",message:"O conector de GTM e GA4 não está disponível neste ambiente. Seus dados permanecem protegidos e nenhuma ação externa foi realizada."}:{title:"Não foi possível carregar o módulo",message:"A conexão falhou antes de carregar os dados. Tente novamente em alguns instantes."})}finally{if(!signal?.aborted)setLoading(false)}},[call,clientId,onSelectClient]);
  useEffect(()=>{const controller=new AbortController();const timer=window.setTimeout(()=>void load(controller.signal),0);return()=>{window.clearTimeout(timer);controller.abort()}},[load]);
  const current=useMemo(()=>clients.find(item=>item.id===clientId),[clients,clientId]);
  async function prepare(){if(!domain.trim()){setNotice("Informe o domínio do cliente.");return}setWorking(true);setNotice("");try{await call({action:"tracking_plan",client_id:clientId,idempotency_key:crypto.randomUUID(),domain,platform,industry,template_key:platform==="kenlo"&&industry==="real_estate"?"real_estate_kenlo_v1":"local_business_v1"},isObject);setNotice("Discovery e plano seguro registrados. Nenhuma alteração foi publicada.");await load()}catch{setNotice("Não foi possível preparar o plano. Revise domínio, plataforma e segmento.")}finally{setWorking(false)}}
  async function discover(){setWorking(true);setNotice("");try{const result=await call({action:"tracking_discover",client_id:clientId},isDiscoveryResult);setNotice(`Discovery real concluído: ${result.resource_count} recurso(s), ${result.legacy_count} legado(s). Nenhuma alteração externa foi feita.`);await load()}catch{setNotice("A conexão Google não respondeu ao discovery. O plano foi preservado para nova tentativa.")}finally{setWorking(false)}}
  async function buildChangePlan(){setWorking(true);setNotice("");try{await call({action:"tracking_change_plan",client_id:clientId,idempotency_key:crypto.randomUUID()},isObject);setNotice("Comparação concluída e validada. O plano continua interno, sem alterações no Google.");await load()}catch{setNotice("Não foi possível validar o plano. Execute o discovery real antes de tentar novamente.")}finally{setWorking(false)}}
  async function requestApproval(deploymentId:string){setWorking(true);setNotice("");try{await call({action:"tracking_request_approval",deployment_id:deploymentId},isObject);setNotice("Plano enviado à Central de Aprovações. Nenhuma tag ou propriedade foi publicada.");await load()}catch{setNotice("O plano precisa passar pela validação prévia antes de entrar na fila.")}finally{setWorking(false)}}
  async function prepareCandidate(deploymentId:string){setWorking(true);setNotice("");try{const result=await call({action:"tracking_candidate",deployment_id:deploymentId,idempotency_key:crypto.randomUUID()},isCandidateResult);setNotice(result.status==="ready"?"Workspace e configuração GA4 candidatos preparados e validados.":"Manifesto preparado. Selecione ou descubra o container GTM e a propriedade GA4 antes da aplicação.");await load()}catch{setNotice("Não foi possível preparar o candidato para este plano.")}finally{setWorking(false)}}
  async function livePreflight(item:Candidate){setWorking(true);setNotice("");try{const result=await call({action:"tracking_live_preflight",deployment_id:item.deployment_id,config_hash:item.config_hash,idempotency_key:crypto.randomUUID()},isPreflightResult);setNotice(result.status==="passed"?`Prévia Google validada. ${result.evidence.key_events_to_prepare.length} evento(s) serão preparados, sem publicação.`:"A prévia encontrou pontos que precisam de revisão.");await load()}catch{setNotice("A prévia exige recursos confirmados e um manifesto pronto.")}finally{setWorking(false)}}
  async function selectResources(){if(!gtmCandidateId||!ga4CandidateId){setNotice("Selecione um container GTM e um stream GA4.");return}setWorking(true);setNotice("");try{await call({action:"tracking_select_resources",client_id:clientId,idempotency_key:crypto.randomUUID(),gtm_candidate_id:gtmCandidateId,ga4_candidate_id:ga4CandidateId},isObject);setNotice("Recursos vinculados ao cliente com auditoria. Nenhuma alteração foi feita no Google.");await load()}catch{setNotice("Não foi possível confirmar os recursos. Execute novamente o discovery e confira a seleção.")}finally{setWorking(false)}}
  async function stageCandidate(item:Candidate){setWorking(true);setNotice("");try{const result=await call({action:"apply_tracking_candidate",deployment_id:item.deployment_id,config_hash:item.config_hash,approved:true},isVersionResult);setNotice(result.version_path?"Tags, acionadores, eventos do GA4 e versão candidata foram preparados. Nada foi publicado.":"Ambiente candidato preparado sem publicação.");await load()}catch{setNotice("A preparação exige aprovação do plano, prévia válida e modo de execução controlada ativo.")}finally{setWorking(false)}}
  async function requestPublish(run:ExecutionRun){setWorking(true);setNotice("");try{await call({action:"request_tracking_publish_approval",run_id:run.id},isObject);setNotice("A versão exata foi enviada para aprovação final de publicação.");await load()}catch{setNotice("A versão candidata precisa estar concluída antes da aprovação final.")}finally{setWorking(false)}}
  async function publishVersion(run:ExecutionRun){setWorking(true);setNotice("");try{await call({action:"publish_tracking_version",run_id:run.id,config_hash:run.config_hash,approved:true},isObject);setNotice("Versão publicada com aprovação registrada. Iniciando etapa de validação.");await load()}catch{setNotice("Publicação bloqueada: confirme a aprovação final e o modo de execução controlada.")}finally{setWorking(false)}}
  async function validateProduction(run:ExecutionRun){setWorking(true);setNotice("");try{const result=await call({action:"tracking_production_validation",run_id:run.id,client_id:clientId},isValidationResult);setNotice(result.validation_status==="passed"?"Tracking validado em produção.":"Configuração publicada; falta detectar o código de medição no site do cliente.");await load()}catch{setNotice("Não foi possível concluir a validação de produção agora.")}finally{setWorking(false)}}
  async function createMissingStack(deploymentId:string,gtmPath:string,ga4Path:string){if(!gtmPath||!ga4Path){setNotice("Escolha a conta GTM e a conta GA4 que receberão os novos recursos.");return}setWorking(true);setNotice("");try{await call({action:"apply_create_tracking_stack",deployment_id:deploymentId,gtm_account:gtmPath,ga4_account:ga4Path,approved:true},isObject);setNotice("Novo container GTM, propriedade e fluxo GA4 preparados e vinculados ao cliente.");await load()}catch{setNotice("A criação exige plano aprovado, contas válidas e modo de execução controlada.")}finally{setWorking(false)}}
  const gtmCandidates=data?.resource_candidates?.filter(item=>item.resource_type==="gtm_container")??[];
  const ga4Candidates=data?.resource_candidates?.filter(item=>item.resource_type==="ga4_web_stream")??[];
  const hasDiscovery=Boolean(data&&(data.resource_candidates?.length||data.resources.length));
  const hasSelection=Boolean(data&&((data.resource_candidates?.some(item=>item.resource_type==="gtm_container"&&item.selected)&&data.resource_candidates?.some(item=>item.resource_type==="ga4_web_stream"&&item.selected))||(data.resources.some(item=>item.resource_type==="gtm_container"&&item.status!=="error")&&data.resources.some(item=>["ga4_property","ga4_web_stream","ga4_measurement"].includes(item.resource_type)&&item.status!=="error"))));
  const hasPlan=Boolean(data?.deployments.length);
  const hasCandidate=Boolean(data?.candidates?.some(item=>item.artifact_type==="validation_report"&&item.status==="ready"));
  const hasPreflight=Boolean(data?.validations.some(item=>item.validator==="google_live_preflight"&&item.status==="passed"));
  const hasExecution=Boolean(data?.execution_runs?.some(item=>item.status==="production_validated"));
  const latestRun=data?.execution_runs?.[0];
  const readyCandidate=data?.candidates?.find(item=>item.artifact_type==="validation_report"&&item.status==="ready");
  const discoveryEvidence=data?.validations.find(item=>item.validator==="alastre_tracking_discovery")?.evidence;
  const availableAccounts=(discoveryEvidence?.available_accounts??{}) as {gtm?:Array<{path:string;name:string}>;ga4?:Array<{path:string;name:string}>};
  const gtmAccounts=availableAccounts.gtm??[];const ga4Accounts=availableAccounts.ga4??[];
  const approvedDeployment=data?.deployments.find(item=>item.status==="approved");
  const hasGtmResource=Boolean(data?.resources.some(item=>item.resource_type==="gtm_container"&&item.status!=="error"));
  const hasGa4Resource=Boolean(data?.resources.some(item=>["ga4_property","ga4_web_stream","ga4_measurement"].includes(item.resource_type)&&item.status!=="error"));
  const guideSteps=[
    {title:"Dados do site",description:"Informe domínio, plataforma e segmento do cliente.",help:"Esses dados definem qual modelo de medição será usado e evitam configurações genéricas.",done:Boolean(data?.profile),target:".tracking-setup",action:"Preencher dados do site"},
    {title:"Descobrir recursos",description:"Localize GTM e GA4 que já existem na conta.",help:"A plataforma consulta a conexão Google em modo de leitura. Nada é criado, alterado ou publicado.",done:hasDiscovery,target:".tracking-grid",action:"Ir para descoberta"},
    {title:"Confirmar GTM e GA4",description:"Confira se os recursos pertencem ao cliente certo.",help:"Esta confirmação impede que um container ou uma propriedade de outro cliente seja usado por engano.",done:hasSelection,target:".tracking-resource-selector",action:"Confirmar recursos"},
    {title:"Comparar configuração",description:"Monte um plano com o que será mantido ou preparado.",help:"O sistema compara o cenário atual com o recomendado e registra as diferenças antes de qualquer execução.",done:hasPlan,target:".tracking-grid",action:"Comparar configuração"},
    {title:"Preparar ambiente",description:"Gere uma configuração candidata, ainda isolada.",help:"É uma versão de trabalho segura para revisão. Ela não altera o site do cliente nem publica tags.",done:hasCandidate,target:".tracking-validations",action:"Preparar ambiente"},
    {title:"Validar prévia",description:"Confirme se o plano continua compatível com o Google.",help:"Uma segunda leitura verifica recursos, eventos e possíveis conflitos antes da aprovação humana.",done:hasPreflight,target:".tracking-validations",action:"Validar prévia"},
    {title:"Aprovar, publicar e validar",description:"Prepare a versão, aprove a publicação e confirme o funcionamento.",help:"O plano prepara tudo isoladamente. Uma segunda aprovação libera somente a versão exata, e a validação final confirma o código no site.",done:hasExecution,target:".tracking-lifecycle",action:"Concluir tracking"},
  ];
  const completedSteps=guideSteps.filter(step=>step.done).length;
  const currentStep=Math.min(guideSteps.findIndex(step=>!step.done)===-1?guideSteps.length-1:guideSteps.findIndex(step=>!step.done),guideSteps.length-1);
  const progress=Math.round(completedSteps/guideSteps.length*100);
  if(loading)return <div className="empty-state">Carregando infraestrutura de mensuração...</div>;
  if(loadError)return <div className="tracking-page"><div className="module-title"><div><div className="eyebrow"><Waypoints/> TRACKING PROVISIONING</div><h1>GTM e GA4</h1><p>Mensuração e governança em um fluxo protegido.</p></div></div><IntegrationState title={loadError.title} message={loadError.message} onRetry={()=>void load()}/></div>;
  return <div className="tracking-page">
    <div className="module-title"><div><div className="eyebrow"><Waypoints/> TRACKING PROVISIONING</div><h1>GTM e GA4</h1><p>Escolha o cliente, descubra a estrutura atual e prepare um plano controlado antes de qualquer publicação.</p></div><select value={clientId} onChange={event=>onSelectClient(event.target.value)}>{clients.map(client=><option key={client.id} value={client.id}>{client.name}</option>)}</select></div>
    <section className="tracking-hero"><div><span className="section-kicker">CLIENTE ATIVO</span><h2>{current?.name??data?.client.name}</h2><p>{data?.profile?.domain??"Tracking ainda não configurado"}</p></div><div className="tracking-health"><Badge variant="outline">{data?.profile?statusLabel[data.profile.status]??data.profile.status:"NÃO INICIADO"}</Badge><strong>{data?.profile?.health==="healthy"?"Saudável":"Preparação"}</strong><span><ShieldCheck/> Escrita externa bloqueada</span></div></section>
    <section className="panel tracking-guide"><div className="guide-heading"><div><span className="section-kicker">ASSISTENTE GUIADO</span><h2>Configure sem precisar conhecer os termos técnicos</h2><p>{completedSteps===guideSteps.length?"Etapas concluídas. A publicação externa continua protegida.":`Agora: ${guideSteps[currentStep].title}. ${guideSteps[currentStep].description}`}</p>{completedSteps<guideSteps.length?<Button className="guide-next-action" onClick={()=>document.querySelector(guideSteps[currentStep].target)?.scrollIntoView({behavior:"smooth",block:"center"})}><Activity/> {guideSteps[currentStep].action}</Button>:null}</div><strong>{progress}% concluído</strong></div><div className="guide-progress" aria-label={`${progress}% concluído`}><span style={{width:`${progress}%`}}/></div><ol className="guide-steps">{guideSteps.map((step,index)=>{const state=step.done?"done":index===currentStep?"current":"next";return <li className={`guide-step ${state}`} key={step.title}><div className="guide-step-top"><span className="guide-number">{step.done?<CheckCircle2/>:index+1}</span><Badge variant="outline">{step.done?"CONCLUÍDO":index===currentStep?"FAÇA AGORA":"DEPOIS"}</Badge></div><strong>{step.title}</strong><p>{step.description}</p><HelpTip title={step.title}>{step.help}</HelpTip></li>})}</ol></section>
    {!data?.profile?<section id="tracking-setup" className="panel tracking-setup"><div className="panel-heading"><div><span className="section-kicker">ETAPA 1 · DADOS DO SITE</span><h2>Preparar infraestrutura</h2><HelpTip title="Preparar infraestrutura">Informe o endereço do site e seu tipo. O sistema usa isso para escolher uma configuração inicial adequada ao cliente.</HelpTip></div><ScanSearch/></div><div className="tracking-form"><label>Domínio<Input value={domain} onChange={e=>setDomain(e.target.value)} placeholder="cliente.com.br"/></label><label>Plataforma<select value={platform} onChange={e=>setPlatform(e.target.value)}><option value="custom">Site próprio / outro</option><option value="wordpress">WordPress</option><option value="kenlo">Kenlo</option><option value="woocommerce">WooCommerce</option><option value="nuvemshop">Nuvemshop</option></select></label><label>Segmento<select value={industry} onChange={e=>setIndustry(e.target.value)}><option value="local_business">Negócio local</option><option value="real_estate">Imobiliária</option><option value="lead_generation">Geração de leads</option><option value="ecommerce">E-commerce</option></select></label></div><Button onClick={prepare} disabled={working}>{working?<RefreshCw className="spin"/>:<ScanSearch/>}{working?"Preparando...":"Executar discovery seguro"}</Button>{notice?<p className="tracking-notice">{notice}</p>:null}</section>:<>
      <section className="tracking-metrics"><article><Globe2/><div><span>Domínio</span><strong>{data.profile.domain}</strong><small>{data.profile.platform} · {data.profile.industry}</small></div></article><article><Network/><div><span>Recursos mapeados</span><strong>{data.resources.length}</strong><small>GTM, GA4 e legados</small></div></article><article><CheckCircle2/><div><span>Validações</span><strong>{data.validations.filter(v=>v.status==="passed").length}/{data.validations.length}</strong><small>Prévia e produção</small></div></article></section>
      <section className="panel tracking-resource-selector"><div className="panel-heading"><div><span className="section-kicker">VÍNCULO CONTROLADO</span><h2>Confirmar recursos do cliente</h2></div><ShieldCheck/></div>{gtmCandidates.length&&ga4Candidates.length?<div className="tracking-selector-grid"><label>Container GTM<select value={gtmCandidateId} onChange={event=>setGtmCandidateId(event.target.value)}>{gtmCandidates.map(item=><option key={item.id} value={item.id}>{item.display_name} · {item.external_id} · {item.confidence}%</option>)}</select><small>{gtmCandidates.find(item=>item.id===gtmCandidateId)?.match_reason}</small></label><label>Stream GA4<select value={ga4CandidateId} onChange={event=>setGa4CandidateId(event.target.value)}>{ga4Candidates.map(item=><option key={item.id} value={item.id}>{item.display_name} · {String(item.metadata.measurement_id??item.external_id)} · {item.confidence}%</option>)}</select><small>{ga4Candidates.find(item=>item.id===ga4CandidateId)?.match_reason}</small></label><Button onClick={selectResources} disabled={working}><ShieldCheck/> Confirmar vínculo seguro</Button></div>:<div className="queue-empty">Execute o discovery real para listar os containers e streams disponíveis na conexão da agência.</div>}</section>
      <section className="tracking-grid"><article className="panel"><div className="panel-heading"><div><span className="section-kicker">INFRAESTRUTURA</span><h2>Recursos descobertos</h2></div><Database/></div>{data.resources.length?data.resources.map(resource=><div className="tracking-row" key={resource.id}><span className={resource.resource_type==="legacy_external_resource"?"tracking-icon warning":"tracking-icon"}>{resource.resource_type==="legacy_external_resource"?<CircleAlert/>:<Network/>}</span><div><strong>{labels[resource.resource_type]??resource.resource_type}</strong><small>{resource.external_id} · {resource.ownership}</small></div><Badge variant="outline">{statusLabel[resource.status]??resource.status}</Badge></div>):<div className="queue-empty">O discovery Google preencherá esta área.</div>}<Button onClick={discover} disabled={working}>{working?<RefreshCw className="spin"/>:<ScanSearch/>}{working?"Consultando...":"Executar discovery real"}</Button></article><article className="panel"><div className="panel-heading"><div><span className="section-kicker">PLANO</span><h2>Provisionamento</h2></div><Activity/></div>{data.deployments.length?data.deployments.map(item=><div className="tracking-plan-card" key={item.id}><div className="tracking-row"><span className="tracking-icon"><Waypoints/></span><div><strong>{statusLabel[item.status]??item.status}</strong><small>{item.decision?.replaceAll("_"," ")} · {new Date(item.created_at).toLocaleString("pt-BR")}</small></div><Badge variant="outline">{item.plan?.safety?.external_writes===false?"SEM ESCRITA":"INTERNO"}</Badge></div>{item.plan?.actions?.length?<div className="tracking-actions">{item.plan.actions.map((action,index)=><div key={`${action.target}-${index}`}><span>{action.target.replaceAll("_"," ")}</span><strong>{operationLabel[action.operation]??action.operation}{typeof action.count==="number"?` · ${action.count}`:""}</strong></div>)}</div>:null}{item.status==="planned"&&!item.approval_id?<Button onClick={()=>void requestApproval(item.id)} disabled={working}><FileCheck2/> Enviar para aprovação</Button>:item.approval_id?<div className="tracking-approval-state"><ShieldCheck/> Vinculado à Central de Aprovações</div>:null}</div>):<div className="queue-empty">Nenhum plano criado.</div>}<div className="tracking-button-row"><Button onClick={buildChangePlan} disabled={working}><Activity/> Comparar e validar plano</Button><Button variant="outline" onClick={prepare} disabled={working}><RefreshCw/> Atualizar base</Button></div>{notice?<p className="tracking-notice">{notice}</p>:null}</article></section>
      <section className="panel tracking-validations"><div className="panel-heading"><div><span className="section-kicker">WORKSPACE CANDIDATO</span><h2>Artefatos preparados</h2></div><Waypoints/></div>{data.candidates?.length?data.candidates.map(item=><div className="tracking-row" key={item.id}><span className={item.status==="ready"?"tracking-icon success":"tracking-icon warning"}>{item.status==="ready"?<CheckCircle2/>:<CircleAlert/>}</span><div><strong>{item.artifact_type.replaceAll("_"," ")}</strong><small>Hash {item.config_hash.slice(0,12)} · {new Date(item.created_at).toLocaleString("pt-BR")}</small></div><Badge variant="outline">{item.status==="ready"?"PRONTO":"AGUARDA RECURSOS"}</Badge></div>):<div className="queue-empty">O manifesto candidato ainda não foi gerado.</div>}<div className="tracking-button-row">{data.deployments.find(item=>["planned","waiting_approval","approved"].includes(item.status))?<Button onClick={()=>void prepareCandidate(data.deployments.find(item=>["planned","waiting_approval","approved"].includes(item.status))!.id)} disabled={working}><Waypoints/> Preparar workspace candidato</Button>:null}{data.candidates?.find(item=>item.artifact_type==="validation_report"&&item.status==="ready")?<Button variant="outline" onClick={()=>void livePreflight(data.candidates.find(item=>item.artifact_type==="validation_report"&&item.status==="ready")!)} disabled={working}><ScanSearch/> Validar prévia no Google</Button>:null}</div>{notice?<p className="tracking-notice">{notice}</p>:null}</section>
      <section className="panel tracking-validations"><div className="panel-heading"><div><span className="section-kicker">EVIDÊNCIAS</span><h2>Validações registradas</h2></div><ShieldCheck/></div>{data.validations.map(item=><div className="tracking-row" key={item.id}><span className={item.status==="passed"?"tracking-icon success":"tracking-icon warning"}>{item.status==="passed"?<CheckCircle2/>:<CircleAlert/>}</span><div><strong>{item.phase} · {item.validator}</strong><small>{new Date(item.validated_at).toLocaleString("pt-BR")}</small></div><Badge variant="outline">{statusLabel[item.status]??item.status}</Badge></div>)}</section>
      <section className="panel tracking-validations"><div className="panel-heading"><div><span className="section-kicker">EXECUÇÃO APROVADA</span><h2>Workspace isolado</h2></div><ShieldCheck/></div>{data.execution_runs?.length?data.execution_runs.map(item=><div className="tracking-row" key={item.id}><span className={item.status==="workspace_created"?"tracking-icon success":"tracking-icon warning"}>{item.status==="workspace_created"?<CheckCircle2/>:<CircleAlert/>}</span><div><strong>{item.status.replaceAll("_"," ")}</strong><small>{item.workspace_path??`Hash ${item.config_hash.slice(0,12)}`} · sem publicação</small></div><Badge variant="outline">ISOLADO</Badge></div>):<div className="queue-empty">Nenhuma execução autorizada. A criação só será liberada após aprovação do mesmo hash.</div>}</section>
      <section className="panel tracking-validations tracking-lifecycle"><div className="panel-heading"><div><span className="section-kicker">CICLO FINAL CONTROLADO</span><h2>Da configuração à validação</h2><HelpTip title="Ciclo final">A plataforma configura o workspace, cria uma versão, pede aprovação específica para publicar e depois verifica se o código está presente no site.</HelpTip></div><ShieldCheck/></div><div className="tracking-lifecycle-steps"><div className={latestRun?.version_path?"done":"current"}><span>1</span><strong>Preparar versão</strong><small>Tags, acionadores e eventos em ambiente isolado.</small></div><div className={latestRun?.publish_approval_id?"done":latestRun?.version_path?"current":"next"}><span>2</span><strong>Aprovar publicação</strong><small>Aprovação humana da versão e do hash exatos.</small></div><div className={latestRun?.status==="published"||latestRun?.status==="production_validated"?"done":latestRun?.status==="publish_approved"?"current":"next"}><span>3</span><strong>Publicar</strong><small>Somente a versão aprovada entra no container ativo.</small></div><div className={latestRun?.status==="production_validated"?"done":latestRun?.status==="published"?"current":"next"}><span>4</span><strong>Validar</strong><small>Confirma versão, GA4 e código instalado no site.</small></div></div><div className="tracking-button-row">{readyCandidate&&(!latestRun||["workspace_created","failed"].includes(latestRun.status))?<Button onClick={()=>void stageCandidate(readyCandidate)} disabled={working}><Waypoints/> Preparar versão candidata</Button>:null}{latestRun?.status==="version_created"?<Button onClick={()=>void requestPublish(latestRun)} disabled={working}><FileCheck2/> Solicitar aprovação para publicar</Button>:null}{latestRun?.status==="waiting_publish_approval"?<Badge variant="outline">AGUARDANDO APROVAÇÃO FINAL</Badge>:null}{latestRun?.status==="publish_approved"?<Button onClick={()=>void publishVersion(latestRun)} disabled={working}><ShieldCheck/> Publicar versão aprovada</Button>:null}{latestRun?.status==="published"?<Button onClick={()=>void validateProduction(latestRun)} disabled={working}><ScanSearch/> Validar em produção</Button>:null}{latestRun?.status==="production_validated"?<div className="tracking-approval-state"><CheckCircle2/> GTM e GA4 concluídos e validados</div>:null}</div><p className="tracking-safety-note"><ShieldCheck/> O primeiro botão nunca publica. A publicação exige uma aprovação separada na Central de Aprovações.</p>{notice?<p className="tracking-notice">{notice}</p>:null}</section>
      {(!hasGtmResource||!hasGa4Resource)&&gtmAccounts.length>0&&ga4Accounts.length>0?<section className="panel tracking-create-stack"><div className="panel-heading"><div><span className="section-kicker">RECURSOS AUSENTES</span><h2>Criar GTM e GA4 novos</h2><HelpTip title="Criar estrutura nova">Use somente quando o cliente não possui recursos adequados. O sistema confere o domínio novamente antes de criar para evitar duplicidade.</HelpTip></div><Database/></div><div className="tracking-selector-grid"><label>Conta que receberá o GTM<select value={gtmAccount||gtmAccounts[0]?.path||""} onChange={event=>setGtmAccount(event.target.value)}>{gtmAccounts.map(item=><option key={item.path} value={item.path}>{item.name} · {item.path}</option>)}</select></label><label>Conta que receberá o GA4<select value={ga4Account||ga4Accounts[0]?.path||""} onChange={event=>setGa4Account(event.target.value)}>{ga4Accounts.map(item=><option key={item.path} value={item.path}>{item.name} · {item.path}</option>)}</select></label>{approvedDeployment?<Button onClick={()=>void createMissingStack(approvedDeployment.id,gtmAccount||gtmAccounts[0]?.path||"",ga4Account||ga4Accounts[0]?.path||"")} disabled={working}><Database/> Criar estrutura aprovada</Button>:<Badge variant="outline">APROVE O PLANO PRIMEIRO</Badge>}</div><p className="tracking-safety-note"><ShieldCheck/> A ação utiliza a aprovação do plano e registra todos os IDs criados na auditoria.</p></section>:null}
    </>}
  </div>;
}
