"use client";
import {useState} from "react";
import {ArrowRight,CalendarDays,CheckCircle2,Clock3,FileSearch,Lightbulb,Link2,Link2Off,ListChecks,MapPin,Plus,Search,ShieldQuestion,Star,Store,Users} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {profileAuditCatalog,unconfiguredLocalRankProvider} from "@/lib/local-seo-v2-domain";
import type {GoogleProfileSnapshot,LocalSeoSection,LocalSeoWorkspace} from "@/lib/local-seo-types";
import type {LocalSeoV2Request} from "@/lib/local-seo-v2-api";

type Ops={posts:Array<Record<string,unknown>>;reviews:Array<Record<string,unknown>>;replies:Array<Record<string,unknown>>;opportunities:Array<Record<string,unknown>>};
const cards:Array<{section:LocalSeoSection;title:string;question:string;action:string;icon:typeof Store}>=[
 {section:"profile",title:"Perfil Google",question:"O perfil está completo e consistente?",action:"Revisar auditoria",icon:Store},
 {section:"reviews",title:"Avaliações",question:"Há avaliações que precisam de resposta?",action:"Abrir avaliações",icon:Star},
 {section:"posts",title:"Postagens",question:"Existe conteúdo planejado para o mês?",action:"Planejar conteúdo",icon:CalendarDays},
 {section:"keywords",title:"Palavras-chave",question:"Quais buscas locais são prioritárias?",action:"Organizar palavras",icon:Search},
 {section:"competitors",title:"Concorrência",question:"Onde o cliente difere dos concorrentes?",action:"Comparar concorrentes",icon:Users},
 {section:"opportunities",title:"Oportunidades",question:"Qual ação tem maior impacto agora?",action:"Ver oportunidades",icon:Lightbulb},
];

export function ExecutiveOverview({workspace,operations,googleStatus,onNavigate,onOpenConnections}:{workspace:LocalSeoWorkspace;operations:Ops;googleStatus:string;onNavigate:(section:LocalSeoSection)=>void;onOpenConnections:()=>void}){
 return <div className="seo-executive"><section className="seo-health-header"><div><span className="section-kicker">CLIENTE</span><h2>{workspace.clientName}</h2><p>Visão executiva da presença local e das próximas ações.</p><Button variant="ghost" onClick={onOpenConnections}><Link2/>Ver conexão Google</Button></div><dl><div><dt>Serviço SEO Local</dt><dd>Em preparação</dd></div><div><dt>Status Google</dt><dd>{googleStatus}</dd></div><div><dt>Última atualização</dt><dd>Não sincronizado</dd></div><div><dt>Saúde dos dados</dt><dd>{workspace.provenance.label}</dd></div></dl></section><section className="seo-executive-grid">{cards.map(card=>{const Icon=card.icon;const amount=card.section==="reviews"?operations.reviews.length:card.section==="posts"?operations.posts.length:card.section==="opportunities"?operations.opportunities.length:null;return <article className="panel seo-executive-card" key={card.section}><div><span><Icon/></span><small>{card.title}</small></div><strong>{amount===null?"N/D":amount}</strong><p>{card.question}</p><div className="executive-answer"><b>Como estamos?</b><span>{amount===null?"Dados ainda insuficientes":amount?`${amount} registro(s) interno(s) disponível(is)`:"Nenhum registro disponível"}</span></div><Button variant="ghost" onClick={()=>onNavigate(card.section)}>{card.action}<ArrowRight/></Button></article>})}</section></div>;
}

const profileValue=(profile:GoogleProfileSnapshot,key:string):unknown=>({name:profile.name,primary_category:profile.primaryCategory,additional_categories:profile.secondaryCategories,description:profile.description,phone:profile.phone,website:profile.website,address:profile.location,hours:profile.hours,services:profile.services,attributes:profile.attributes,photos:profile.photos,completeness:profile.completeness}[key]);
export function ProfileAudit({workspace,googleConnected,checks=[],clientId,onSave}:{workspace:LocalSeoWorkspace;googleConnected:boolean;checks?:Array<Record<string,unknown>>;clientId:string;onSave?:(input:LocalSeoV2Request)=>Promise<void>}){const persisted=new Map(checks.map(item=>[String(item.check_key),item]));return <div className="seo-operation"><section className="operation-head"><div><span className="section-kicker">AUDITORIA DO PERFIL</span><h2>Perfil Google</h2><p>Verificações manuais com evidência e histórico persistente.</p></div><span className="audit-summary"><ListChecks/> {checks.length} verificações registradas</span></section><div className="profile-audit-grid">{profileAuditCatalog.map(([key,label])=>{const value=profileValue(workspace.profile,key),saved=persisted.get(key),status=String(saved?.status??"not_verified"),available=Array.isArray(value)?value.length>0:value!==null&&value!==undefined&&value!=="";return <article className="panel profile-check" key={key}><span className={`check-state ${status==="ok"?"known":"unknown"}`}>{status==="ok"?<CheckCircle2/>:googleConnected?<Clock3/>:<Link2Off/>}</span><div><strong>{label}</strong><small>{status.replaceAll("_"," ")}</small><p>{String(saved?.evidence_note??(available?Array.isArray(value)?value.join(" · "):value:"Sem evidência registrada."))}</p>{onSave&&<select aria-label={`Estado de ${label}`} value={status} onChange={event=>void onSave({action:"audit_save",client_id:clientId,check_key:key,status:event.target.value as "ok"|"attention"|"critical"|"not_verified"|"not_available",source:"manual",evidence_note:available?String(Array.isArray(value)?value.join(" · "):value):undefined})}><option value="not_verified">Não verificado</option><option value="not_available">Indisponível</option><option value="ok">OK</option><option value="attention">Atenção</option><option value="critical">Crítico</option></select>}</div><b>{status.toUpperCase().replaceAll("_"," ")}</b></article>})}</div></div>}

export function KeywordsWorkspace({clientId,rows,onSave}:{clientId:string;rows:Array<Record<string,unknown>>;onSave?:(input:LocalSeoV2Request)=>Promise<void>}){const [keyword,setKeyword]=useState("");const visible=rows.filter(row=>row.status!=="archived");return <div className="seo-operation"><section className="operation-head"><div><span className="section-kicker">DEMANDA LOCAL</span><h2>Palavras-chave</h2><p>Cadastre, aprove e monitore termos reais da operação.</p></div></section>{onSave&&<section className="panel operation-head"><Input value={keyword} onChange={event=>setKeyword(event.target.value)} placeholder="Ex.: agência de marketing em Santo André"/><Button disabled={!keyword.trim()} onClick={()=>{void onSave({action:"keyword_save",client_id:clientId,keyword,intent:"local",priority:"medium",source:"manual"});setKeyword("")}}><Plus/>Adicionar</Button></section>}<div className="keyword-lanes">{["monitored","suggested","approved"].map(status=><section className="panel" key={status}><strong>{status==="monitored"?"Monitoradas":status==="suggested"?"Sugeridas":"Aprovadas"}</strong>{visible.filter(row=>row.status===status).map(row=><span key={String(row.id)}>{String(row.keyword)} {onSave&&status==="suggested"&&<button onClick={()=>void onSave({action:"keyword_status",client_id:clientId,id:String(row.id),status:"approved"})}>Aprovar</button>} {onSave&&<button onClick={()=>void onSave({action:"keyword_status",client_id:clientId,id:String(row.id),status:"archived"})}>Arquivar</button>}</span>)}{!visible.some(row=>row.status===status)&&<span>Nenhum registro</span>}</section>)}</div><section className="panel rank-foundation"><MapPin/><div><span className="section-kicker">RANK TRACKING</span><h3>Monitoramento de posições ainda não configurado.</h3><p>Não exibimos posições sem um provider real.</p></div><span>{unconfiguredLocalRankProvider.status}</span></section></div>}

export function CompetitorsWorkspace({clientId,rows,onSave}:{clientId:string;rows:Array<Record<string,unknown>>;onSave?:(input:LocalSeoV2Request)=>Promise<void>}){const [name,setName]=useState("");const active=rows.filter(row=>row.status!=="archived");return <div className="seo-operation"><section className="operation-head"><div><span className="section-kicker">CENÁRIO LOCAL</span><h2>Concorrentes</h2><p>Cadastre referências manualmente e compare somente dados comprovados.</p></div></section>{onSave&&<section className="panel operation-head"><Input value={name} onChange={event=>setName(event.target.value)} placeholder="Nome do concorrente"/><Button disabled={!name.trim()} onClick={()=>{void onSave({action:"competitor_save",client_id:clientId,name});setName("")}}><Plus/>Adicionar</Button></section>}{active.length===0?<section className="panel competitor-empty"><Users/><div><h3>Nenhum concorrente cadastrado</h3><p>Adicione uma referência conhecida para iniciar a comparação.</p></div><span>Sem descoberta automática ou scraping</span></section>:<section className="panel comparison-table">{active.map(row=><div className="comparison-row" key={String(row.id)}><strong>{String(row.name)}</strong><span>{String(row.location??"Local não informado")}</span><b>{row.rating==null?"N/D":String(row.rating)}</b>{onSave&&<button onClick={()=>void onSave({action:"competitor_status",client_id:clientId,id:String(row.id),status:"archived"})}>Arquivar</button>}</div>)}</section>}</div>}

export function HistoryWorkspace(){return <section className="panel local-empty"><span><FileSearch/></span><div><h2>Histórico operacional</h2><p>Scores, auditorias, recomendações, aprovações e ações serão organizados em uma linha do tempo quando houver registros persistidos.</p><small><ShieldQuestion/> Nenhum evento fictício foi criado.</small></div></section>}
