"use client";
import {ArrowRight,BarChart3,CalendarDays,CheckCircle2,Clock3,FileSearch,Lightbulb,Link2,Link2Off,ListChecks,MapPin,Plus,Search,ShieldQuestion,Star,Store,Users} from "lucide-react";
import {Button} from "@/components/ui/button";
import {profileAuditCatalog,unconfiguredLocalRankProvider} from "@/lib/local-seo-v2-domain";
import type {GoogleProfileSnapshot,LocalSeoSection,LocalSeoWorkspace} from "@/lib/local-seo-types";

type Ops={posts:Array<Record<string,unknown>>;reviews:Array<Record<string,unknown>>;replies:Array<Record<string,unknown>>;opportunities:Array<Record<string,unknown>>};
const cards:Array<{section:LocalSeoSection;title:string;question:string;action:string;icon:typeof Store}>=[
 {section:"profile",title:"Perfil Google",question:"O perfil está completo e consistente?",action:"Revisar auditoria",icon:Store},
 {section:"reviews",title:"Avaliações",question:"Há avaliações que precisam de resposta?",action:"Abrir avaliações",icon:Star},
 {section:"posts",title:"Postagens",question:"Existe conteúdo planejado para o mês?",action:"Planejar conteúdo",icon:CalendarDays},
 {section:"keywords",title:"Palavras-chave",question:"Quais buscas locais são prioritárias?",action:"Organizar palavras",icon:Search},
 {section:"competitors",title:"Concorrência",question:"Onde o cliente difere dos concorrentes?",action:"Comparar concorrentes",icon:Users},
 {section:"opportunities",title:"Oportunidades",question:"Qual ação tem maior impacto agora?",action:"Ver oportunidades",icon:Lightbulb},
];

export function ExecutiveOverview({workspace,operations,googleStatus,onNavigate,onOpenConnections}:{workspace:LocalSeoWorkspace;operations:Ops;googleStatus:string;onNavigate:(section:LocalSeoSection)=>void;onOpenConnections:()=>void}){
 return <div className="seo-executive"><section className="seo-health-header"><div><span className="section-kicker">CLIENTE</span><h2>{workspace.clientName}</h2><p>Visão executiva da presença local e das próximas ações.</p><Button variant="ghost" onClick={onOpenConnections}><Link2/>Ver conexão Google</Button></div><dl><div><dt>Serviço SEO Local</dt><dd>Em preparação</dd></div><div><dt>Status Google</dt><dd>{googleStatus}</dd></div><div><dt>Última atualização</dt><dd>Não sincronizado</dd></div><div><dt>Saúde dos dados</dt><dd>{workspace.provenance.label}</dd></div></dl></section><section className="seo-executive-grid">{cards.map(card=>{const Icon=card.icon;const amount=card.section==="reviews"?operations.reviews.length:card.section==="posts"?operations.posts.length:card.section==="opportunities"?operations.opportunities.length:null;return <article className="panel seo-executive-card" key={card.section}><div><span><Icon/></span><small>{card.title}</small></div><strong>{amount===null?"N/D":amount}</strong><p>{card.question}</p><div className="executive-answer"><b>Como estamos?</b><span>{amount===null?"Dados ainda insuficientes":amount?`${amount} registro(s) interno(s) disponível(is)`:"Nenhum registro disponível"}</span></div><Button variant="ghost" onClick={()=>onNavigate(card.section)}>{card.action}<ArrowRight/></Button></article>})}</section></div>;
}

const profileValue=(profile:GoogleProfileSnapshot,key:string):unknown=>({name:profile.name,primary_category:profile.primaryCategory,additional_categories:profile.secondaryCategories,description:profile.description,phone:profile.phone,website:profile.website,address:profile.location,hours:profile.hours,services:profile.services,attributes:profile.attributes,photos:profile.photos,completeness:profile.completeness}[key]);
export function ProfileAudit({workspace,googleConnected}:{workspace:LocalSeoWorkspace;googleConnected:boolean}){return <div className="seo-operation"><section className="operation-head"><div><span className="section-kicker">AUDITORIA DO PERFIL</span><h2>Perfil Google</h2><p>Verificações operacionais com estado, evidência e próxima ação.</p></div><span className="audit-summary"><ListChecks/> {googleConnected?"Sincronização pendente":"Integração não conectada"}</span></section><div className="profile-audit-grid">{profileAuditCatalog.map(([key,label])=>{const value=profileValue(workspace.profile,key),available=Array.isArray(value)?value.length>0:value!==null&&value!==undefined&&value!=="";return <article className="panel profile-check" key={key}><span className={`check-state ${available?"known":"unknown"}`}>{available?<CheckCircle2/>:googleConnected?<Clock3/>:<Link2Off/>}</span><div><strong>{label}</strong><small>{available?"Informação disponível no DNA":"Não verificado"}</small><p>{available?Array.isArray(value)?value.join(" · "):String(value):googleConnected?"Aguardando sincronização para verificar.":"Esta verificação depende de uma fonte conectada."}</p></div><b>{available?"ATENÇÃO":googleConnected?"PENDENTE":"INDISPONÍVEL"}</b></article>})}</div></div>}

export function KeywordsWorkspace(){return <div className="seo-operation"><section className="operation-head"><div><span className="section-kicker">DEMANDA LOCAL</span><h2>Palavras-chave</h2><p>Organize termos por intenção, serviço, localidade, prioridade e fonte.</p></div><Button disabled><Plus/>Adicionar palavra-chave</Button></section><div className="keyword-lanes"><section className="panel"><strong>Monitoradas</strong><span>Nenhuma palavra monitorada</span></section><section className="panel"><strong>Sugeridas</strong><span>Nenhuma sugestão gerada</span></section><section className="panel"><strong>Aprovadas</strong><span>Nenhuma palavra aprovada</span></section></div><section className="panel rank-foundation"><MapPin/><div><span className="section-kicker">RANK TRACKING</span><h3>Monitoramento de posições ainda não configurado.</h3><p>O ranking local utilizará um provider próprio. A API do Perfil Google não é tratada como fonte de posição.</p></div><span>{unconfiguredLocalRankProvider.status}</span></section><section className="panel rank-table"><header><strong>Palavra-chave</strong><strong>Posição</strong><strong>Data</strong><strong>Localização</strong><strong>Variação</strong></header><div><Search/><span>Não há medições reais. Posição, variação e mapa aparecerão como N/D até a primeira coleta.</span></div></section></div>}

export function CompetitorsWorkspace(){return <div className="seo-operation"><section className="operation-head"><div><span className="section-kicker">CENÁRIO LOCAL</span><h2>Concorrentes</h2><p>Cadastre referências locais manualmente e compare somente dados comprovados.</p></div><Button disabled><Plus/>Adicionar concorrente</Button></section><section className="panel competitor-empty"><Users/><div><h3>Nenhum concorrente cadastrado</h3><p>Nome, categoria, localização, nota, avaliações, website, observações, fonte e atualização aparecerão aqui.</p></div><span>Descoberta automática futura · sem scraping</span></section><section className="panel comparison-table"><div className="panel-heading"><div><span className="section-kicker">COMPARAÇÃO COMPETITIVA</span><h3>Cliente vs. concorrentes</h3></div><BarChart3/></div><div className="comparison-head"><strong>Dimensão</strong><strong>Cliente</strong><strong>Concorrentes</strong></div>{["Avaliações","Nota","Conteúdo","Categorias","Perfil","Autoridade","Posição local"].map(item=><div className="comparison-row" key={item}><span>{item}</span><b>N/D</b><b>N/D</b></div>)}</section></div>}

export function HistoryWorkspace(){return <section className="panel local-empty"><span><FileSearch/></span><div><h2>Histórico operacional</h2><p>Scores, auditorias, recomendações, aprovações e ações serão organizados em uma linha do tempo quando houver registros persistidos.</p><small><ShieldQuestion/> Nenhum evento fictício foi criado.</small></div></section>}
