import { z } from "zod";
import type {
  EconomicAssumption,
  CostRecord,
  CapacitySimulationResult,
  SegregatedMarginResult,
  PricingEvaluationResult,
  DataOrigin,
  CostCategory,
  OperationalRole,
  DiscountType,
  ApprovalStatus,
} from "./capacity-and-finance-domain.ts";

export const CreateEconomicAssumptionSchema = z.object({
  cost_type: z.enum([
    "labor",
    "software",
    "ai",
    "customer_service",
    "sales",
    "implementation",
    "rework",
    "other_operational",
  ]),
  value: z.number().min(0, "O valor deve ser maior ou igual a zero"),
  currency: z.string().default("BRL"),
  period: z.enum(["hourly", "daily", "monthly", "yearly", "per_unit", "per_ticket"]).default("monthly"),
  origin: z.enum(["real_observed", "reported_value", "estimate", "hypothesis", "unavailable"]).default("hypothesis"),
  evidence_reference: z.string().optional().nullable(),
  hypothesis_description: z.string().optional().nullable(),
  responsible_name: z.string().min(2, "Informe o responsável pela premissa"),
  effective_date: z.string().default(() => new Date().toISOString().split("T")[0]),
});

export const RunCapacitySimulationSchema = z.object({
  scenario_clients_count: z.number().int().positive(),
  roles: z.array(
    z.object({
      role: z.enum(["client", "client_service", "analyst", "specialist", "manager", "automation_ai"]),
      available_monthly_hours_per_head: z.number().positive().default(160),
      headcount: z.number().int().positive().default(1),
      estimated_minutes_per_client: z.number().min(0),
      actual_minutes_per_client: z.number().min(0).optional().nullable(),
      rework_minutes_per_client: z.number().min(0).optional().nullable(),
      sla_fulfillment_pct: z.number().min(0).max(100).optional().nullable(),
    })
  ),
});

export const CalculateMarginSchema = z.object({
  client_id: z.string().optional().nullable(),
  product_definition_id: z.string().optional().nullable(),
  proposal_id: z.string().optional().nullable(),
  contracted_value: z.number().min(0),
  invoiced_value: z.number().min(0).optional().nullable(),
  received_value: z.number().min(0).optional().nullable(),
  estimated_cost: z.number().min(0),
  actual_cost: z.number().min(0).optional().nullable(),
});

export const EvaluatePricingSchema = z.object({
  proposal_id: z.string().min(1, "Informe a proposta"),
  product_definition_id: z.string().optional().nullable(),
  list_setup_price: z.number().min(0),
  list_monthly_price: z.number().min(0),
  proposed_setup_price: z.number().min(0),
  proposed_monthly_price: z.number().min(0),
  estimated_operational_cost: z.number().min(0),
  discount_applied_pct: z.number().min(0).max(100).default(0),
  discount_type: z.enum([
    "scope_reduction",
    "frequency_reduction",
    "support_reduction",
    "contractual_tradeoff",
    "unjustified",
  ]).optional().nullable(),
  discount_counterpart_description: z.string().optional().nullable(),
  is_cost_estimated: z.boolean().default(false),
  is_counterpart_documented: z.boolean().default(false),
});

export const ProcessPricingApprovalSchema = z.object({
  approval_item_id: z.string().min(1, "ID de aprovação é obrigatório"),
  decision: z.enum(["approved", "rejected"]),
  decision_note: z.string().optional().nullable(),
});

export const CapacityFinanceActionSchema = z.discriminatedUnion("action", [
  z.object({
    action: z.literal("create_assumption"),
    payload: CreateEconomicAssumptionSchema,
  }),
  z.object({
    action: z.literal("run_capacity_simulation"),
    payload: RunCapacitySimulationSchema,
  }),
  z.object({
    action: z.literal("calculate_margin"),
    payload: CalculateMarginSchema,
  }),
  z.object({
    action: z.literal("evaluate_pricing"),
    payload: EvaluatePricingSchema,
  }),
  z.object({
    action: z.literal("process_pricing_approval"),
    payload: ProcessPricingApprovalSchema,
  }),
]);

export type CapacityFinanceActionInput = z.infer<typeof CapacityFinanceActionSchema>;

// Baseline In-Memory Store for quick fallback execution and unit testing
export const capacityFinanceMemoryStore = {
  assumptions: [
    {
      id: "assump-001",
      agency_id: "a1a57e00-0000-4000-8000-000000000001",
      cost_type: "labor" as CostCategory,
      value: 65.0,
      currency: "BRL",
      period: "hourly" as const,
      origin: "real_observed" as DataOrigin,
      evidence_reference: "Folha de Pagamento - Contrato Analista SEO 2026",
      hypothesis_description: null,
      responsible_name: "Financeiro Alastre",
      effective_date: "2026-01-01",
      version: 1,
      approval_status: "approved" as ApprovalStatus,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "assump-002",
      agency_id: "a1a57e00-0000-4000-8000-000000000001",
      cost_type: "software" as CostCategory,
      value: 450.0,
      currency: "BRL",
      period: "monthly" as const,
      origin: "reported_value" as DataOrigin,
      evidence_reference: "Fatura SaaS Provedores SEO & Maps v2026",
      hypothesis_description: null,
      responsible_name: "Operações Alastre",
      effective_date: "2026-01-01",
      version: 1,
      approval_status: "approved" as ApprovalStatus,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "assump-003",
      agency_id: "a1a57e00-0000-4000-8000-000000000001",
      cost_type: "ai" as CostCategory,
      value: 0.15,
      currency: "BRL",
      period: "per_ticket" as const,
      origin: "hypothesis" as DataOrigin,
      evidence_reference: null,
      hypothesis_description: "Estimativa de consumo de tokens por geração de postagem/resposta",
      responsible_name: "Tech Leads",
      effective_date: "2026-02-01",
      version: 1,
      approval_status: "approved" as ApprovalStatus,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ] as EconomicAssumption[],

  costs: [
    {
      id: "cost-001",
      agency_id: "a1a57e00-0000-4000-8000-000000000001",
      client_id: "b10a1a00-0000-4000-8000-000000000001",
      product_definition_id: "prod-seo-local-v1",
      cost_category: "labor" as CostCategory,
      operational_role: "analyst" as OperationalRole,
      delivery_mode: "recurring" as const,
      estimated_minutes: 480,
      actual_minutes: 510,
      estimated_cost: 520.0,
      actual_cost: 552.5,
      currency: "BRL",
      origin: "real_observed" as DataOrigin,
      assumption_id: "assump-001",
      notes: "Horas de analista dedicadas ao SEO Local recorrente",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ] as CostRecord[],

  simulations: [
    {
      id: "sim-10",
      agency_id: "a1a57e00-0000-4000-8000-000000000001",
      scenario_clients_count: 10,
      operational_role: "analyst" as OperationalRole,
      available_monthly_hours: 160.0,
      planned_monthly_hours: 80.0,
      actual_monthly_hours: 85.0,
      rework_monthly_hours: 5.0,
      sla_fulfillment_pct: 98.0,
      occupancy_rate_pct: 50.0,
      is_dominant_bottleneck: true,
      quality_risk_level: "low" as const,
      hiring_trigger_clients: 17,
      data_coverage_status: "complete" as const,
      missing_data_fields: [],
      calculated_at: new Date().toISOString(),
    },
    {
      id: "sim-25",
      agency_id: "a1a57e00-0000-4000-8000-000000000001",
      scenario_clients_count: 25,
      operational_role: "analyst" as OperationalRole,
      available_monthly_hours: 160.0,
      planned_monthly_hours: 200.0,
      actual_monthly_hours: 212.5,
      rework_monthly_hours: 15.0,
      sla_fulfillment_pct: 88.0,
      occupancy_rate_pct: 125.0,
      is_dominant_bottleneck: true,
      quality_risk_level: "critical" as const,
      hiring_trigger_clients: 17,
      data_coverage_status: "complete" as const,
      missing_data_fields: [],
      calculated_at: new Date().toISOString(),
    },
    {
      id: "sim-50",
      agency_id: "a1a57e00-0000-4000-8000-000000000001",
      scenario_clients_count: 50,
      operational_role: "analyst" as OperationalRole,
      available_monthly_hours: 320.0,
      planned_monthly_hours: 400.0,
      actual_monthly_hours: 420.0,
      rework_monthly_hours: 30.0,
      sla_fulfillment_pct: 82.0,
      occupancy_rate_pct: 125.0,
      is_dominant_bottleneck: true,
      quality_risk_level: "critical" as const,
      hiring_trigger_clients: 34,
      data_coverage_status: "complete" as const,
      missing_data_fields: [],
      calculated_at: new Date().toISOString(),
    },
    {
      id: "sim-100",
      agency_id: "a1a57e00-0000-4000-8000-000000000001",
      scenario_clients_count: 100,
      operational_role: "analyst" as OperationalRole,
      available_monthly_hours: 640.0,
      planned_monthly_hours: 800.0,
      actual_monthly_hours: 840.0,
      rework_monthly_hours: 60.0,
      sla_fulfillment_pct: 78.0,
      occupancy_rate_pct: 125.0,
      is_dominant_bottleneck: true,
      quality_risk_level: "critical" as const,
      hiring_trigger_clients: 68,
      data_coverage_status: "complete" as const,
      missing_data_fields: [],
      calculated_at: new Date().toISOString(),
    },
  ] as CapacitySimulationResult[],

  margins: [
    {
      id: "margin-001",
      agency_id: "a1a57e00-0000-4000-8000-000000000001",
      client_id: "b10a1a00-0000-4000-8000-000000000001",
      product_definition_id: "prod-seo-local-v1",
      contracted_value: 2500.0,
      invoiced_value: 2500.0,
      received_value: 2500.0,
      estimated_cost: 970.0,
      actual_cost: 1002.5,
      estimated_margin_value: 1530.0,
      actual_margin_value: 1497.5,
      estimated_margin_pct: 61.2,
      actual_margin_pct: 59.9,
      hiring_break_even_clients: 17,
      quality_degradation_risk: "low" as const,
      data_coverage_status: "complete" as const,
      missing_data_fields: [],
      analyzed_at: new Date().toISOString(),
    },
  ] as SegregatedMarginResult[],

  pricingDecisions: [] as (PricingEvaluationResult & { id: string; agency_id: string; approval_item_id?: string | null })[],
};
