import {z} from "zod";
export const connectionStatuses=["pending","connected","attention","expired","revoked","error","disconnected"] as const;
export const syncStatuses=["idle","syncing","success","error"] as const;
export type ConnectionStatus=typeof connectionStatuses[number];
export type ProviderKey="google"|"meta"|"alastre_ai"|"electronic_signature"|"email";
export type CapabilityKey="google_business_profile"|"google_ads"|"google_analytics"|"google_tag_manager"|"meta_ads"|"facebook_pages"|"instagram_business"|"ai_generation";
export type ProviderDefinition={key:ProviderKey;name:string;group:"Google"|"Meta"|"IA"|"Futuro";description:string;availability:"ready"|"planned"|"included";capabilities:Array<{key:CapabilityKey;name:string;help:string}>};
export const providers:ProviderDefinition[]=[
 {key:"google",name:"Google",group:"Google",description:"Uma única autorização para encontrar os serviços e empresas permitidos.",availability:"ready",capabilities:[{key:"google_business_profile",name:"Perfil da Empresa",help:"A ficha da empresa que aparece no Google e no Google Maps."},{key:"google_ads",name:"Google Ads",help:"Contas de anúncios e campanhas autorizadas."},{key:"google_analytics",name:"Google Analytics",help:"Propriedades usadas para medir visitas e resultados."},{key:"google_tag_manager",name:"Google Tag Manager",help:"Contêineres que organizam a mensuração do site."}]},
 {key:"meta",name:"Meta",group:"Meta",description:"Prepare anúncios e presenças do Facebook e Instagram em um só lugar.",availability:"planned",capabilities:[{key:"meta_ads",name:"Meta Ads",help:"Contas de anúncios autorizadas."},{key:"facebook_pages",name:"Facebook",help:"Páginas comerciais disponíveis."},{key:"instagram_business",name:"Instagram",help:"Contas profissionais vinculadas."}]},
 {key:"alastre_ai",name:"IA Alastre",group:"IA",description:"Assistência inteligente incluída e administrada pela Alastre Platform.",availability:"included",capabilities:[{key:"ai_generation",name:"IA Alastre",help:"Geração assistida com as proteções e contexto da plataforma."}]},
 {key:"electronic_signature",name:"Assinatura eletrônica",group:"Futuro",description:"Assinaturas com provedores compatíveis, sem dependência de uma única marca.",availability:"planned",capabilities:[]},
 {key:"email",name:"E-mail",group:"Futuro",description:"Comunicação e automações de e-mail conectadas à operação.",availability:"planned",capabilities:[]},
];
export const statusCopy:Record<ConnectionStatus,{label:string;detail:string}>={pending:{label:"Preparando conexão",detail:"Falta concluir a autorização."},connected:{label:"Conectado",detail:"A conexão está funcionando normalmente."},attention:{label:"Precisa de atenção",detail:"Há uma etapa simples para corrigir."},expired:{label:"Reconexão necessária",detail:"Precisamos reconectar sua conta."},revoked:{label:"Acesso removido",detail:"A autorização não está mais ativa."},error:{label:"Problema na conexão",detail:"Encontramos um problema e preservamos seus dados."},disconnected:{label:"Não conectado",detail:"Conecte quando quiser ativar estes serviços."}};
const id=z.string().uuid();
export const connectionHubRequest=z.discriminatedUnion("action",[z.object({action:z.literal("providers")}),z.object({action:z.literal("connections")}),z.object({action:z.literal("connection_status"),connection_id:id}),z.object({action:z.literal("capabilities"),connection_id:id}),z.object({action:z.literal("resources"),connection_id:id,capability:z.string().trim().max(80).optional()}),z.object({action:z.literal("bindings"),client_id:id.optional()}),z.object({action:z.literal("client_connection"),client_id:id,capability:z.enum(["google_business_profile","google_ads","google_analytics","google_tag_manager","meta_ads","facebook_pages","instagram_business","ai_generation"])}),z.object({action:z.literal("prepare_authorization"),provider:z.enum(["google","meta"])}),z.object({action:z.literal("bind_resource"),client_id:id,resource_id:id,capability:z.string().trim().min(2).max(80)}),z.object({action:z.literal("health"),connection_id:id.optional()})]);
export function canBindResource(input:{clientAgencyId:string;resourceAgencyId:string;resourceCapability:string;requestedCapability:string;resourceActive:boolean}){return input.clientAgencyId===input.resourceAgencyId&&input.resourceCapability===input.requestedCapability&&input.resourceActive;}
export function getClientConnectionContract(clientId:string,capability:CapabilityKey){return {client_id:clientId,capability,requires_status:"connected" as const};}
