export type SkillStatus = "audited" | "installed" | "active" | "disabled" | "rejected" | "incompatible";
export type SkillScope = "Projeto" | "Usuário" | "Sistema" | "Ferramenta";
export type SkillCategory = "Design" | "Produto" | "Agentes" | "Segurança" | "SEO Local" | "Arquitetura" | "Ferramentas";
export type SkillRecord = {
  id:string; name:string; category:SkillCategory; status:SkillStatus; scope:SkillScope; origin:string; version:string;
  license:string; path:string; purpose:string; triggers:string[]; whenNot:string; risks:string; scriptsHooks:string;
  dependencies:string; compatibility:string; invocation:"Automática"|"Manual"|"Automática e manual";
};

export const statusLabels:Record<SkillStatus,string>={audited:"Auditada",installed:"Instalada",active:"Ativa",disabled:"Desativada",rejected:"Rejeitada",incompatible:"Incompatível"};
const project=".agents/skills";
const safe={license:"Interna",scriptsHooks:"Nenhum",dependencies:"Nenhuma",compatibility:"Codex nativo (.agents/skills)",invocation:"Automática" as const};
const owl={scope:"Projeto" as const,origin:"Owl-Listener/ai-design-skills",version:"f41b650435b62dec6d5b1dc3598ac4679f8b7ae7 (perfil Alastre)",license:"MIT",status:"active" as const,scriptsHooks:"Nenhum instalado; build.py e pre-commit existem apenas no upstream",dependencies:"Nenhuma",compatibility:"Agent Skill instruction-only compatível com Codex",invocation:"Automática e manual" as const};
const owlRisk="Orientação externa subordinada ao AGENTS.md e às skills internas Alastre; não concede permissões.";

export const skillRegistry:SkillRecord[]=[
  {...safe,id:"alastre-product-ux",name:"Alastre Product UX",category:"Produto",status:"active",scope:"Projeto",origin:"Alastre Digital",version:"1.1.0",path:`${project}/alastre-product-ux`,purpose:"Mantém interfaces claras, responsivas, premium e honestas para pessoas não técnicas.",triggers:["Interface","Fluxo","Responsividade","Estado vazio"],whenNot:"Tarefas somente de backend.",risks:"Prevalece sobre orientações visuais externas em caso de conflito."},
  {...safe,id:"alastre-security-review",name:"Alastre Security Review",category:"Segurança",status:"active",scope:"Projeto",origin:"Alastre Digital",version:"1.2.0",path:`${project}/alastre-security-review`,purpose:"Protege tenants, credenciais, aprovações e ações externas.",triggers:["API","Dados","Integração","Permissão","OAuth"],whenNot:"Mudanças visuais sem dados ou efeitos externos.",risks:"Tem precedência sobre recomendações externas; revisão não autoriza escrita."},
  {...safe,id:"alastre-local-seo",name:"Alastre Local SEO",category:"SEO Local",status:"active",scope:"Projeto",origin:"Alastre Digital",version:"1.2.0",path:`${project}/alastre-local-seo`,purpose:"Orienta SEO Local com evidências reais, confiança e Local Score explicável.",triggers:["SEO Local","Perfil Google","Local Score","Avaliações"],whenNot:"SEO não local ou mídia paga isolada.",risks:"Não inventa ranking, não transforma N/D em zero e não publica sem autorização."},
  {...safe,id:"alastre-saas-architecture",name:"Alastre SaaS Architecture",category:"Arquitetura",status:"active",scope:"Projeto",origin:"Alastre Digital",version:"1.2.0",path:`${project}/alastre-saas-architecture`,purpose:"Mantém a plataforma modular, multi-tenant e preparada para escala.",triggers:["Arquitetura","SaaS","Contrato","Provider"],whenNot:"Ajustes visuais simples.",risks:"Não executa migrations ou mudanças remotas."},
  {id:"frontend-design",name:"Frontend Design",category:"Design",status:"active",scope:"Projeto",origin:"anthropics/skills",version:"34040c9c568585f6929bedeaad110ad08f079624",license:"Apache-2.0",path:`${project}/frontend-design`,purpose:"Define direção visual para interfaces novas ou reformulações substanciais.",triggers:["Nova interface","Nova linguagem visual","Redesign substancial"],whenNot:"Correção pontual ou revisão final.",risks:"A identidade Alastre prevalece.",scriptsHooks:"Nenhum no diretório instalado",dependencies:"Nenhuma",compatibility:"Agent Skill reconhecida pelo Codex",invocation:"Automática e manual"},
  {id:"impeccable",name:"Impeccable — perfil seguro",category:"Design",status:"active",scope:"Projeto",origin:"Adaptado de pbakaus/impeccable",version:"4.3.1-alastre.1 @ cb56ed6c19a07329a9fa0cd4e657bee040156593",license:"Apache-2.0",path:`${project}/impeccable`,purpose:"Revisa acabamento, hierarquia, espaçamento, legibilidade e responsividade.",triggers:["Finalização","Polimento","QA visual"],whenNot:"Backend ou redesign sem direção.",risks:"Launcher, binário e hooks upstream foram removidos.",scriptsHooks:"Nenhum instalado",dependencies:"Nenhuma",compatibility:"Perfil instruction-only para Codex/Windows",invocation:"Automática e manual"},
  {...owl,id:"context-window-design",name:"Context Window Design",category:"Agentes",path:`${project}/context-window-design`,purpose:"Define o que carregar, resumir, persistir e buscar sob demanda.",triggers:["DNA","Memória","Contexto","RAG"],whenNot:"Tarefa curta sem contexto acumulado.",risks:owlRisk},
  {...owl,id:"conversation-patterns",name:"Conversation Patterns",category:"Agentes",path:`${project}/conversation-patterns`,purpose:"Padroniza esclarecimento, confirmação, erro, recuperação e handoff.",triggers:["Conversa","Erro","Handoff","Assistência"],whenNot:"Processamento sem interação humana.",risks:owlRisk},
  {...owl,id:"mixed-initiative-flow",name:"Mixed Initiative Flow",category:"Segurança",path:`${project}/mixed-initiative-flow`,purpose:"Define quando a IA propõe, o humano decide e o sistema executa.",triggers:["Ação externa","Autonomia","Handoff","Aprovação"],whenNot:"Leitura determinística sem efeito.",risks:"Adaptada: aprovação e execução são estados distintos; escrita externa segue bloqueada."},
  {...owl,id:"feedback-loops",name:"Feedback Loops",category:"Agentes",path:`${project}/feedback-loops`,purpose:"Organiza correções e preferências sem aprendizado crítico silencioso.",triggers:["Feedback","Correção","Preferência","Aprendizado"],whenNot:"Evento sem efeito futuro.",risks:"Adaptada: regras críticas só mudam com propósito, auditoria e revisão humana."},
  {...owl,id:"system-prompt-structure",name:"System Prompt Structure",category:"Agentes",path:`${project}/system-prompt-structure`,purpose:"Estrutura identidade, contexto, regras, limites e saída de agentes.",triggers:["Criar agente","System prompt","Revisar agente"],whenNot:"Prompt casual de uso único.",risks:"Adaptada: não solicita nem expõe chain-of-thought privado."},
  {...owl,id:"template-design",name:"Template Design",category:"Agentes",path:`${project}/template-design`,purpose:"Cria prompts parametrizados, tipados, versionáveis e seguros.",triggers:["Template","Prompt versionado","Variáveis"],whenNot:"Instrução simples sem reuso.",risks:"Adaptada: variável ausente falha com segurança e template não autoriza ação."},
  {...owl,id:"constraint-specification",name:"Constraint Specification",category:"Segurança",path:`${project}/constraint-specification`,purpose:"Transforma regras vagas em limites priorizados e testáveis.",triggers:["Constraints","Política","Formato","Limite"],whenNot:"Preferência puramente editorial.",risks:"Adaptada: prompt não substitui enforcement server-side."},
  {...owl,id:"few-shot-patterns",name:"Few-shot Patterns",category:"Agentes",path:`${project}/few-shot-patterns`,purpose:"Usa exemplos bons, ruins e limítrofes de modo controlado.",triggers:["Exemplos","Calibrar saída","Edge case"],whenNot:"Quando instruções claras já bastam.",risks:"Adaptada: somente dados fictícios ou sanitizados; exemplos não concedem permissões."},
  {...owl,id:"guardrail-design",name:"Guardrail Design",category:"Segurança",path:`${project}/guardrail-design`,purpose:"Projeta bloqueios, avisos, recusas e escalonamento proporcional ao risco.",triggers:["Guardrail","Ação externa","Segredo","Escopo"],whenNot:"Preferência visual sem risco.",risks:"Adaptada: Alastre Security Review prevalece e controles server-side continuam obrigatórios."},
  {...owl,id:"trust-calibration",name:"Trust Calibration",category:"Segurança",path:`${project}/trust-calibration`,purpose:"Diferencia fato, inferência, dado parcial, sugestão e desconhecido.",triggers:["Confiança","Dado parcial","Inferência","Evidência"],whenNot:"Resultado determinístico diretamente verificável.",risks:"Adaptada: confiança deriva de cobertura real, nunca de porcentagem cosmética."},
  {...owl,id:"transparency-patterns",name:"Transparency Patterns",category:"Segurança",path:`${project}/transparency-patterns`,purpose:"Mostra origem, limites e estado do dado em linguagem humana.",triggers:["Transparência","Proveniência","Estado do dado"],whenNot:"Detalhe interno sem valor para decisão.",risks:"Adaptada: expõe evidências e resumo decisório, nunca chain-of-thought privado."},
  {id:"chain-of-thought-design",name:"Chain of Thought Design",category:"Agentes",status:"rejected",scope:"Projeto",origin:"Owl-Listener/ai-design-skills",version:"f41b650435b62dec6d5b1dc3598ac4679f8b7ae7",license:"MIT",path:"Não instalado",purpose:"Propõe cadeias explícitas de raciocínio.",triggers:["Nenhum — rejeitada"],whenNot:"Todos os fluxos Alastre.",risks:"Conflita com a política de não solicitar, armazenar ou expor raciocínio interno.",scriptsHooks:"Nenhum no diretório candidato",dependencies:"Nenhuma",compatibility:"Formato compatível; política incompatível",invocation:"Manual"},
  {id:"taste-skill",name:"Taste Skill",category:"Design",status:"incompatible",scope:"Projeto",origin:"Leonxlnx/taste-skill",version:"ccbc15639c97057cbfcf32ecebc38ef716e4bb37",license:"MIT",path:"Não instalado",purpose:"Direção estética para landing pages e portfólios.",triggers:["Landing page"],whenNot:"Dashboards e produto multi-etapas.",risks:"O próprio upstream exclui o núcleo da Alastre Platform.",scriptsHooks:"Scripts upstream não executados",dependencies:"Nenhuma instalada",compatibility:"Finalidade incompatível",invocation:"Manual"},
  {id:"progressive-disclosure",name:"Progressive Disclosure externa V1.1",category:"Design",status:"incompatible",scope:"Projeto",origin:"Neeeophytee/finding-unknowns-skills",version:"6d7dda2a7b6d50db6a0da3a8b7899dea7f2856cd",license:"MIT",path:"Não instalado",purpose:"Divide arquivos grandes de instrução, não interfaces.",triggers:["Spec grande"],whenNot:"Progressive disclosure de produto.",risks:"Semântica incompatível com o uso solicitado.",scriptsHooks:"Scripts upstream não executados",dependencies:"Nenhuma",compatibility:"Formato compatível; finalidade incompatível",invocation:"Manual"},
  {id:"playwright",name:"QA visual do navegador",category:"Ferramentas",status:"active",scope:"Ferramenta",origin:"Codex Unified Computer Use",version:"fornecida pelo ambiente",license:"Gerenciada pelo Codex",path:"Ferramenta, não Skill",purpose:"Inspeciona a interface real sem adicionar pacote ao projeto.",triggers:["QA visual","Navegação"],whenNot:"Teste unitário ou backend.",risks:"Playwright não está instalado no projeto.",scriptsHooks:"Nenhum no repositório",dependencies:"Nenhuma nova",compatibility:"Disponível nesta sessão",invocation:"Automática"},
];

export const skillWorkflows=[
  {name:"Criar agente",steps:["System Prompt Structure","Template Design","Few-shot Patterns","Constraint Specification"]},
  {name:"Revisar agente",steps:["System Prompt Structure","Constraint Specification","Alastre Security Review quando sensível"]},
  {name:"Ação externa segura",steps:["Mixed Initiative Flow","Guardrail Design","Alastre Security Review","Aprovação humana"]},
  {name:"SEO Local",steps:["Alastre Local SEO","Trust Calibration","Transparency Patterns"]},
  {name:"Arquitetura SaaS",steps:["Alastre SaaS Architecture","Alastre Security Review"]},
  {name:"Análise com dados parciais",steps:["Trust Calibration","Transparency Patterns"]},
  {name:"Feedback e aprendizado",steps:["Feedback Loops","Governança e auditoria","Revisão humana quando crítica"]},
];
