import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";

/**
 * Product Factory Drizzle Schema (SQLite/D1 mirror for Alastre Platform)
 */

export const productDefinitions = sqliteTable("product_definitions", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  name: text("name").notNull(),
  slug: text("slug").notNull(),
  category: text("category").notNull(),
  description: text("description").notNull(),
  version: integer("version").notNull().default(1),
  status: text("status").notNull().default("draft"),
  is_immutable: integer("is_immutable", { mode: "boolean" }).notNull().default(false),
  approved_at: text("approved_at"),
  approved_by: text("approved_by"),
  metadata: text("metadata", { mode: "json" }),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const productDiscoverySessions = sqliteTable("product_discovery_sessions", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  product_id: text("product_id").notNull(),
  current_round: integer("current_round").notNull().default(1),
  max_rounds: integer("max_rounds").notNull().default(3),
  status: text("status").notNull().default("in_progress"),
  notes: text("notes"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const productScopeItems = sqliteTable("product_scope_items", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  product_id: text("product_id").notNull(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  scope_type: text("scope_type").notNull(),
  frequency: text("frequency").notNull().default("one_off"),
  delivery_type: text("delivery_type").notNull(),
  estimated_minutes: integer("estimated_minutes").notNull().default(0),
  automation_percentage: integer("automation_percentage").notNull().default(0),
  tooling_required: text("tooling_required", { mode: "json" }),
  acceptance_criteria: text("acceptance_criteria").notNull(),
  required_evidence: text("required_evidence").notNull(),
  order_index: integer("order_index").notNull().default(0),
  status: text("status").notNull().default("active"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const productOperationalSops = sqliteTable("product_operational_sops", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  product_id: text("product_id").notNull(),
  scope_item_id: text("scope_item_id"),
  title: text("title").notNull(),
  trigger_condition: text("trigger_condition").notNull(),
  inputs_required: text("inputs_required", { mode: "json" }),
  step_by_step_checklist: text("step_by_step_checklist", { mode: "json" }),
  expected_output: text("expected_output").notNull(),
  common_deviations_and_fixes: text("common_deviations_and_fixes", { mode: "json" }),
  mandatory_evidence: text("mandatory_evidence").notNull(),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const productRaciAssignments = sqliteTable("product_raci_assignments", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  product_id: text("product_id").notNull(),
  scope_item_id: text("scope_item_id"),
  activity_name: text("activity_name").notNull(),
  responsible: text("responsible").notNull(),
  accountable: text("accountable").notNull(),
  consulted: text("consulted", { mode: "json" }),
  informed: text("informed", { mode: "json" }),
  notes: text("notes"),
  is_future_role: integer("is_future_role", { mode: "boolean" }).notNull().default(false),
  future_role_title: text("future_role_title"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const productViabilityCheckpoints = sqliteTable("product_viability_checkpoints", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  product_id: text("product_id").notNull(),
  discovery_completeness_percentage: integer("discovery_completeness_percentage").notNull().default(0),
  total_setup_minutes: integer("total_setup_minutes").notNull().default(0),
  total_monthly_minutes: integer("total_monthly_minutes").notNull().default(0),
  automatable_percentage: integer("automatable_percentage").notNull().default(0),
  blocking_gaps: text("blocking_gaps", { mode: "json" }),
  viability_score: integer("viability_score").notNull().default(0),
  result: text("result").notNull(),
  explanation: text("explanation").notNull(),
  calculated_at: text("calculated_at").notNull(),
  calculated_by: text("calculated_by"),
});

/**
 * Commercial & CRM Drizzle Schema (SQLite/D1 mirror for Alastre Platform)
 */

export const commercialCompanies = sqliteTable("commercial_companies", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  name: text("name").notNull(),
  trade_name: text("trade_name"),
  segment: text("segment"),
  city: text("city"),
  state_uf: text("state_uf"),
  website: text("website"),
  phone: text("phone"),
  identity_key: text("identity_key").notNull(),
  maps_url: text("maps_url"),
  place_id: text("place_id"),
  cid: text("cid"),
  rating: text("rating"),
  review_count: integer("review_count"),
  observed_profile_quality: text("observed_profile_quality").notNull().default("incomplete"),
  units_count: integer("units_count").notNull().default(1),
  notes: text("notes").notNull().default(""),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const commercialContacts = sqliteTable("commercial_contacts", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  company_id: text("company_id").notNull(),
  name: text("name").notNull(),
  role_title: text("role_title").notNull().default(""),
  phone: text("phone"),
  email: text("email"),
  is_decision_maker: integer("is_decision_maker", { mode: "boolean" }).notNull().default(false),
  is_primary: integer("is_primary", { mode: "boolean" }).notNull().default(false),
  notes: text("notes").notNull().default(""),
  created_at: text("created_at").notNull(),
});

export const commercialOpportunities = sqliteTable("commercial_opportunities", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  company_id: text("company_id").notNull(),
  title: text("title").notNull(),
  stage: text("stage").notNull().default("new"),
  priority: text("priority").notNull().default("media_prioridade"),
  origin: text("origin").notNull().default("prospecting"),
  product_definition_id: text("product_definition_id"),
  product_version: integer("product_version").notNull().default(1),
  responsible_actor_id: text("responsible_actor_id").notNull(),
  responsible_name: text("responsible_name").notNull(),
  last_activity_at: text("last_activity_at").notNull(),
  next_action: text("next_action").notNull(),
  next_action_deadline: text("next_action_deadline").notNull(),
  estimated_setup_value: text("estimated_setup_value"),
  estimated_mrr_value: text("estimated_mrr_value"),
  blocking_reason: text("blocking_reason"),
  closed_at: text("closed_at"),
  loss_reason_code: text("loss_reason_code"),
  loss_reason_details: text("loss_reason_details"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const commercialAssessments = sqliteTable("commercial_assessments", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  opportunity_id: text("opportunity_id").notNull(),
  type: text("type").notNull(),
  fit_score: text("fit_score"),
  intent_score: text("intent_score"),
  opportunity_score: text("opportunity_score"),
  priority_result: text("priority_result"),
  qualification_result: text("qualification_result"),
  dimensions: text("dimensions", { mode: "json" }),
  evidences: text("evidences", { mode: "json" }),
  hypotheses: text("hypotheses", { mode: "json" }),
  gaps: text("gaps", { mode: "json" }),
  explanation: text("explanation").notNull().default(""),
  assessed_by_actor_id: text("assessed_by_actor_id").notNull(),
  assessed_at: text("assessed_at").notNull(),
});

export const commercialDiagnoses = sqliteTable("commercial_diagnoses", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  opportunity_id: text("opportunity_id").notNull(),
  step_answers: text("step_answers", { mode: "json" }),
  evidences: text("evidences", { mode: "json" }),
  expectations: text("expectations").notNull().default(""),
  red_flags: text("red_flags", { mode: "json" }),
  risks: text("risks", { mode: "json" }),
  decision: text("decision").notNull().default(""),
  next_steps: text("next_steps").notNull().default(""),
  conducted_by_actor_id: text("conducted_by_actor_id").notNull(),
  conducted_at: text("conducted_at").notNull(),
});

export const commercialProposals = sqliteTable("commercial_proposals", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  opportunity_id: text("opportunity_id").notNull(),
  product_definition_id: text("product_definition_id").notNull(),
  product_version: integer("product_version").notNull().default(1),
  version: integer("version").notNull().default(1),
  status: text("status").notNull().default("draft"),
  is_immutable: integer("is_immutable", { mode: "boolean" }).notNull().default(false),
  setup_price: text("setup_price").notNull().default("0.00"),
  monthly_price: text("monthly_price").notNull().default("0.00"),
  discount_setup_percentage: text("discount_setup_percentage").notNull().default("0.00"),
  discount_monthly_percentage: text("discount_monthly_percentage").notNull().default("0.00"),
  discount_justification: text("discount_justification"),
  discount_counterpart: text("discount_counterpart"),
  scope_adjustments: text("scope_adjustments", { mode: "json" }),
  selected_scope_items: text("selected_scope_items", { mode: "json" }),
  payment_terms: text("payment_terms").notNull().default(""),
  valid_until: text("valid_until").notNull(),
  dependencies: text("dependencies", { mode: "json" }),
  expectations: text("expectations", { mode: "json" }),
  risks: text("risks", { mode: "json" }),
  sent_at: text("sent_at"),
  decided_at: text("decided_at"),
  created_by_actor_id: text("created_by_actor_id").notNull(),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const commercialActivities = sqliteTable("commercial_activities", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  opportunity_id: text("opportunity_id").notNull(),
  cadence: text("cadence").notNull(),
  title: text("title").notNull(),
  objective: text("objective").notNull(),
  status: text("status").notNull().default("pending"),
  deadline: text("deadline").notNull(),
  completed_at: text("completed_at"),
  actor_id: text("actor_id").notNull(),
  notes: text("notes").notNull().default(""),
  created_at: text("created_at").notNull(),
});

export const commercialSalesHandoffs = sqliteTable("commercial_sales_handoffs", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  opportunity_id: text("opportunity_id").notNull(),
  company_id: text("company_id").notNull(),
  proposal_id: text("proposal_id").notNull(),
  status: text("status").notNull().default("draft"),
  checklist: text("checklist", { mode: "json" }),
  promises_made: text("promises_made").notNull().default(""),
  client_expectations: text("client_expectations").notNull().default(""),
  operational_risks: text("operational_risks").notNull().default(""),
  critical_dependencies: text("critical_dependencies").notNull().default(""),
  missing_data: text("missing_data").notNull().default(""),
  operations_reviewer_actor_id: text("operations_reviewer_actor_id"),
  operations_notes: text("operations_notes"),
  submitted_at: text("submitted_at"),
  reviewed_at: text("reviewed_at"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

