import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";

/**
 * Product Factory Drizzle Schema (SQLite/D1 mirror for Alastre Platform)
 */

export const productDefinitions = sqliteTable("product_definitions", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  name: text("name").notNull(),
  slug: text("slug").notNull(),
  category: text("category").notNull(),
  description: text("description").notNull(),
  version: integer("version").notNull().default(1),
  status: text("status").notNull().default("draft"),
  is_immutable: integer("is_immutable", { mode: "boolean" }).notNull().default(false),
  approved_at: text("approved_at"),
  approved_by: text("approved_by"),
  metadata: text("metadata", { mode: "json" }),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const productDiscoverySessions = sqliteTable("product_discovery_sessions", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  product_id: text("product_id").notNull(),
  current_round: integer("current_round").notNull().default(1),
  max_rounds: integer("max_rounds").notNull().default(3),
  status: text("status").notNull().default("in_progress"),
  notes: text("notes"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const productScopeItems = sqliteTable("product_scope_items", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  product_id: text("product_id").notNull(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  scope_type: text("scope_type").notNull(),
  frequency: text("frequency").notNull().default("one_off"),
  delivery_type: text("delivery_type").notNull(),
  estimated_minutes: integer("estimated_minutes").notNull().default(0),
  automation_percentage: integer("automation_percentage").notNull().default(0),
  tooling_required: text("tooling_required", { mode: "json" }),
  acceptance_criteria: text("acceptance_criteria").notNull(),
  required_evidence: text("required_evidence").notNull(),
  order_index: integer("order_index").notNull().default(0),
  status: text("status").notNull().default("active"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const productOperationalSops = sqliteTable("product_operational_sops", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  product_id: text("product_id").notNull(),
  scope_item_id: text("scope_item_id"),
  title: text("title").notNull(),
  trigger_condition: text("trigger_condition").notNull(),
  inputs_required: text("inputs_required", { mode: "json" }),
  step_by_step_checklist: text("step_by_step_checklist", { mode: "json" }),
  expected_output: text("expected_output").notNull(),
  common_deviations_and_fixes: text("common_deviations_and_fixes", { mode: "json" }),
  mandatory_evidence: text("mandatory_evidence").notNull(),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const productRaciAssignments = sqliteTable("product_raci_assignments", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  product_id: text("product_id").notNull(),
  scope_item_id: text("scope_item_id"),
  activity_name: text("activity_name").notNull(),
  responsible: text("responsible").notNull(),
  accountable: text("accountable").notNull(),
  consulted: text("consulted", { mode: "json" }),
  informed: text("informed", { mode: "json" }),
  notes: text("notes"),
  is_future_role: integer("is_future_role", { mode: "boolean" }).notNull().default(false),
  future_role_title: text("future_role_title"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const productViabilityCheckpoints = sqliteTable("product_viability_checkpoints", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  product_id: text("product_id").notNull(),
  discovery_completeness_percentage: integer("discovery_completeness_percentage").notNull().default(0),
  total_setup_minutes: integer("total_setup_minutes").notNull().default(0),
  total_monthly_minutes: integer("total_monthly_minutes").notNull().default(0),
  automatable_percentage: integer("automatable_percentage").notNull().default(0),
  blocking_gaps: text("blocking_gaps", { mode: "json" }),
  viability_score: integer("viability_score").notNull().default(0),
  result: text("result").notNull(),
  explanation: text("explanation").notNull(),
  calculated_at: text("calculated_at").notNull(),
  calculated_by: text("calculated_by"),
});

/**
 * Commercial & CRM Drizzle Schema (SQLite/D1 mirror for Alastre Platform)
 */

export const commercialCompanies = sqliteTable("commercial_companies", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  name: text("name").notNull(),
  trade_name: text("trade_name"),
  segment: text("segment"),
  city: text("city"),
  state_uf: text("state_uf"),
  website: text("website"),
  phone: text("phone"),
  identity_key: text("identity_key").notNull(),
  maps_url: text("maps_url"),
  place_id: text("place_id"),
  cid: text("cid"),
  rating: text("rating"),
  review_count: integer("review_count"),
  observed_profile_quality: text("observed_profile_quality").notNull().default("incomplete"),
  units_count: integer("units_count").notNull().default(1),
  notes: text("notes").notNull().default(""),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const commercialContacts = sqliteTable("commercial_contacts", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  company_id: text("company_id").notNull(),
  name: text("name").notNull(),
  role_title: text("role_title").notNull().default(""),
  phone: text("phone"),
  email: text("email"),
  is_decision_maker: integer("is_decision_maker", { mode: "boolean" }).notNull().default(false),
  is_primary: integer("is_primary", { mode: "boolean" }).notNull().default(false),
  notes: text("notes").notNull().default(""),
  created_at: text("created_at").notNull(),
});

export const commercialOpportunities = sqliteTable("commercial_opportunities", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  company_id: text("company_id").notNull(),
  title: text("title").notNull(),
  stage: text("stage").notNull().default("new"),
  priority: text("priority").notNull().default("media_prioridade"),
  origin: text("origin").notNull().default("prospecting"),
  product_definition_id: text("product_definition_id"),
  product_version: integer("product_version").notNull().default(1),
  responsible_actor_id: text("responsible_actor_id").notNull(),
  responsible_name: text("responsible_name").notNull(),
  last_activity_at: text("last_activity_at").notNull(),
  next_action: text("next_action").notNull(),
  next_action_deadline: text("next_action_deadline").notNull(),
  estimated_setup_value: text("estimated_setup_value"),
  estimated_mrr_value: text("estimated_mrr_value"),
  blocking_reason: text("blocking_reason"),
  closed_at: text("closed_at"),
  loss_reason_code: text("loss_reason_code"),
  loss_reason_details: text("loss_reason_details"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const commercialAssessments = sqliteTable("commercial_assessments", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  opportunity_id: text("opportunity_id").notNull(),
  type: text("type").notNull(),
  fit_score: text("fit_score"),
  intent_score: text("intent_score"),
  opportunity_score: text("opportunity_score"),
  priority_result: text("priority_result"),
  qualification_result: text("qualification_result"),
  dimensions: text("dimensions", { mode: "json" }),
  evidences: text("evidences", { mode: "json" }),
  hypotheses: text("hypotheses", { mode: "json" }),
  gaps: text("gaps", { mode: "json" }),
  explanation: text("explanation").notNull().default(""),
  assessed_by_actor_id: text("assessed_by_actor_id").notNull(),
  assessed_at: text("assessed_at").notNull(),
});

export const commercialDiagnoses = sqliteTable("commercial_diagnoses", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  opportunity_id: text("opportunity_id").notNull(),
  step_answers: text("step_answers", { mode: "json" }),
  evidences: text("evidences", { mode: "json" }),
  expectations: text("expectations").notNull().default(""),
  red_flags: text("red_flags", { mode: "json" }),
  risks: text("risks", { mode: "json" }),
  decision: text("decision").notNull().default(""),
  next_steps: text("next_steps").notNull().default(""),
  conducted_by_actor_id: text("conducted_by_actor_id").notNull(),
  conducted_at: text("conducted_at").notNull(),
});

export const commercialProposals = sqliteTable("commercial_proposals", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  opportunity_id: text("opportunity_id").notNull(),
  product_definition_id: text("product_definition_id").notNull(),
  product_version: integer("product_version").notNull().default(1),
  version: integer("version").notNull().default(1),
  status: text("status").notNull().default("draft"),
  is_immutable: integer("is_immutable", { mode: "boolean" }).notNull().default(false),
  setup_price: text("setup_price").notNull().default("0.00"),
  monthly_price: text("monthly_price").notNull().default("0.00"),
  discount_setup_percentage: text("discount_setup_percentage").notNull().default("0.00"),
  discount_monthly_percentage: text("discount_monthly_percentage").notNull().default("0.00"),
  discount_justification: text("discount_justification"),
  discount_counterpart: text("discount_counterpart"),
  scope_adjustments: text("scope_adjustments", { mode: "json" }),
  selected_scope_items: text("selected_scope_items", { mode: "json" }),
  payment_terms: text("payment_terms").notNull().default(""),
  valid_until: text("valid_until").notNull(),
  dependencies: text("dependencies", { mode: "json" }),
  expectations: text("expectations", { mode: "json" }),
  risks: text("risks", { mode: "json" }),
  sent_at: text("sent_at"),
  decided_at: text("decided_at"),
  created_by_actor_id: text("created_by_actor_id").notNull(),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const commercialActivities = sqliteTable("commercial_activities", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  opportunity_id: text("opportunity_id").notNull(),
  cadence: text("cadence").notNull(),
  title: text("title").notNull(),
  objective: text("objective").notNull(),
  status: text("status").notNull().default("pending"),
  deadline: text("deadline").notNull(),
  completed_at: text("completed_at"),
  actor_id: text("actor_id").notNull(),
  notes: text("notes").notNull().default(""),
  created_at: text("created_at").notNull(),
});

export const commercialSalesHandoffs = sqliteTable("commercial_sales_handoffs", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  opportunity_id: text("opportunity_id").notNull(),
  company_id: text("company_id").notNull(),
  proposal_id: text("proposal_id").notNull(),
  status: text("status").notNull().default("draft"),
  checklist: text("checklist", { mode: "json" }),
  promises_made: text("promises_made").notNull().default(""),
  client_expectations: text("client_expectations").notNull().default(""),
  operational_risks: text("operational_risks").notNull().default(""),
  critical_dependencies: text("critical_dependencies").notNull().default(""),
  missing_data: text("missing_data").notNull().default(""),
  operations_reviewer_actor_id: text("operations_reviewer_actor_id"),
  operations_notes: text("operations_notes"),
  submitted_at: text("submitted_at"),
  reviewed_at: text("reviewed_at"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

/**
 * Client Onboarding Drizzle Schema (SQLite/D1 mirror for Alastre Platform)
 */

export const clientOnboardings = sqliteTable("client_onboardings", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  client_id: text("client_id"),
  opportunity_id: text("opportunity_id"),
  sales_handoff_id: text("sales_handoff_id"),
  proposal_id: text("proposal_id"),
  product_definition_id: text("product_definition_id"),
  product_version: integer("product_version").notNull().default(1),
  status: text("status").notNull().default("draft"),
  current_stage: text("current_stage").notNull().default("draft"),
  divergence_reason: text("divergence_reason"),
  blocking_reason: text("blocking_reason"),
  commercial_scope_snapshot: text("commercial_scope_snapshot", { mode: "json" }),
  created_by_actor_id: text("created_by_actor_id").notNull(),
  assigned_operator_actor_id: text("assigned_operator_actor_id"),
  idempotency_key: text("idempotency_key"),
  activated_at: text("activated_at"),
  activated_by_actor_id: text("activated_by_actor_id"),
  activation_approval_id: text("activation_approval_id"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const clientUnits = sqliteTable("client_units", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  client_id: text("client_id").notNull(),
  onboarding_id: text("onboarding_id"),
  name: text("name").notNull(),
  unit_type: text("unit_type").notNull().default("headquarters"),
  is_physical_store: integer("is_physical_store", { mode: "boolean" }).notNull().default(true),
  has_service_area: integer("has_service_area", { mode: "boolean" }).notNull().default(false),
  service_radius_km: text("service_radius_km"),
  status: text("status").notNull().default("active"),
  phone: text("phone"),
  email: text("email"),
  address_street: text("address_street"),
  address_number: text("address_number"),
  address_complement: text("address_complement"),
  neighborhood: text("neighborhood"),
  city: text("city").notNull(),
  state_uf: text("state_uf").notNull(),
  postal_code: text("postal_code"),
  latitude: text("latitude"),
  longitude: text("longitude"),
  business_hours: text("business_hours", { mode: "json" }),
  gbp_place_id: text("gbp_place_id"),
  gbp_location_id: text("gbp_location_id"),
  gbp_cid: text("gbp_cid"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const clientOnboardingRequirements = sqliteTable("client_onboarding_requirements", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  onboarding_id: text("onboarding_id").notNull(),
  client_id: text("client_id"),
  unit_id: text("unit_id"),
  category: text("category").notNull(),
  title: text("title").notNull(),
  description: text("description").notNull().default(""),
  responsible: text("responsible").notNull().default("client"),
  is_required: integer("is_required", { mode: "boolean" }).notNull().default(true),
  blocks_activation: integer("blocks_activation", { mode: "boolean" }).notNull().default(true),
  status: text("status").notNull().default("pending"),
  deadline: text("deadline"),
  evidence_text: text("evidence_text"),
  evidence_url: text("evidence_url"),
  notes: text("notes").notNull().default(""),
  waived_reason: text("waived_reason"),
  verified_by_actor_id: text("verified_by_actor_id"),
  verified_at: text("verified_at"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const clientOnboardingBaselines = sqliteTable("client_onboarding_baselines", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  onboarding_id: text("onboarding_id").notNull(),
  client_id: text("client_id").notNull(),
  unit_id: text("unit_id"),
  version: integer("version").notNull().default(1),
  source: text("source").notNull().default("manual_audit"),
  profile_completeness_score: integer("profile_completeness_score"),
  current_rating: text("current_rating"),
  current_review_count: integer("current_review_count"),
  unanswered_reviews_count: integer("unanswered_reviews_count"),
  ranking_visibility_notes: text("ranking_visibility_notes").notNull().default(""),
  content_audit: text("content_audit", { mode: "json" }),
  tracked_keywords: text("tracked_keywords", { mode: "json" }),
  known_competitors: text("known_competitors", { mode: "json" }),
  available_conversions: text("available_conversions", { mode: "json" }),
  collection_limitations: text("collection_limitations", { mode: "json" }),
  unavailable_data_points: text("unavailable_data_points", { mode: "json" }),
  established_by_actor_id: text("established_by_actor_id").notNull(),
  established_at: text("established_at").notNull(),
  created_at: text("created_at").notNull(),
});

export const clientOnboardingPlans = sqliteTable("client_onboarding_plans", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  onboarding_id: text("onboarding_id").notNull(),
  client_id: text("client_id").notNull(),
  product_definition_id: text("product_definition_id").notNull(),
  product_version: integer("product_version").notNull().default(1),
  status: text("status").notNull().default("draft"),
  items: text("items", { mode: "json" }),
  total_setup_minutes: integer("total_setup_minutes").notNull().default(0),
  total_recurring_monthly_minutes: integer("total_recurring_monthly_minutes").notNull().default(0),
  target_start_date: text("target_start_date"),
  target_activation_date: text("target_activation_date"),
  planned_by_actor_id: text("planned_by_actor_id").notNull(),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const clientOnboardingDecisions = sqliteTable("client_onboarding_decisions", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  onboarding_id: text("onboarding_id").notNull(),
  decision_type: text("decision_type").notNull(),
  actor_id: text("actor_id").notNull(),
  actor_name: text("actor_name").notNull(),
  actor_role: text("actor_role").notNull(),
  reason: text("reason").notNull(),
  metadata: text("metadata", { mode: "json" }),
  decided_at: text("decided_at").notNull(),
});

/**
 * Module 04: Operations Engine Drizzle Schema
 */

export const workflowTemplates = sqliteTable("workflow_templates", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  product_definition_id: text("product_definition_id"),
  name: text("name").notNull(),
  slug: text("slug").notNull(),
  version: integer("version").notNull().default(1),
  category: text("category").notNull().default("general"),
  description: text("description").notNull().default(""),
  trigger_type: text("trigger_type").notNull().default("manual"),
  target_service: text("target_service"),
  is_active: integer("is_active", { mode: "boolean" }).notNull().default(true),
  estimated_total_minutes: integer("estimated_total_minutes").notNull().default(0),
  definition: text("definition", { mode: "json" }),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const workflows = sqliteTable("workflows", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  client_id: text("client_id").notNull(),
  unit_id: text("unit_id"),
  service_id: text("service_id"),
  template_id: text("template_id"),
  title: text("title").notNull(),
  workflow_type: text("workflow_type").notNull().default("implementation"),
  status: text("status").notNull().default("pending"),
  priority: text("priority").notNull().default("medium"),
  progress_percentage: integer("progress_percentage").notNull().default(0),
  total_estimated_minutes: integer("total_estimated_minutes").notNull().default(0),
  total_actual_minutes: integer("total_actual_minutes").notNull().default(0),
  blocked_reason: text("blocked_reason"),
  target_start_date: text("target_start_date"),
  target_due_date: text("target_due_date"),
  started_at: text("started_at"),
  completed_at: text("completed_at"),
  assigned_actor_id: text("assigned_actor_id"),
  metadata: text("metadata", { mode: "json" }),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const workItems = sqliteTable("work_items", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  client_id: text("client_id").notNull(),
  workflow_id: text("workflow_id").notNull(),
  unit_id: text("unit_id"),
  title: text("title").notNull(),
  description: text("description").notNull().default(""),
  task_type: text("task_type").notNull().default("manual"),
  frequency: text("frequency").notNull().default("one_off"),
  status: text("status").notNull().default("todo"),
  priority: text("priority").notNull().default("medium"),
  estimated_minutes: integer("estimated_minutes").notNull().default(0),
  actual_minutes: integer("actual_minutes").notNull().default(0),
  due_date: text("due_date"),
  sla_hours: integer("sla_hours").default(24),
  sla_status: text("sla_status").notNull().default("on_track"),
  depends_on_item_ids: text("depends_on_item_ids", { mode: "json" }),
  assigned_actor_id: text("assigned_actor_id"),
  assigned_actor_name: text("assigned_actor_name"),
  requires_approval: integer("requires_approval", { mode: "boolean" }).notNull().default(false),
  approval_item_id: text("approval_item_id"),
  evidence_required: integer("evidence_required", { mode: "boolean" }).notNull().default(false),
  evidence_text: text("evidence_text"),
  evidence_url: text("evidence_url"),
  acceptance_criteria: text("acceptance_criteria").notNull().default(""),
  sop_reference: text("sop_reference"),
  blocked_reason: text("blocked_reason"),
  client_action_required: text("client_action_required"),
  completed_at: text("completed_at"),
  completed_by_actor_id: text("completed_by_actor_id"),
  order_index: integer("order_index").notNull().default(0),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const workItemTimeLogs = sqliteTable("work_item_time_logs", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  client_id: text("client_id").notNull(),
  work_item_id: text("work_item_id").notNull(),
  actor_id: text("actor_id").notNull(),
  actor_name: text("actor_name").notNull(),
  minutes_spent: integer("minutes_spent").notNull(),
  notes: text("notes").notNull().default(""),
  logged_at: text("logged_at").notNull(),
  created_at: text("created_at").notNull(),
});

export const operationalExceptions = sqliteTable("operational_exceptions", {
  id: text("id").primaryKey(),
  agency_id: text("agency_id").notNull(),
  client_id: text("client_id").notNull(),
  workflow_id: text("workflow_id"),
  work_item_id: text("work_item_id"),
  severity: text("severity").notNull(),
  status: text("status").notNull().default("open"),
  category: text("category").notNull(),
  description: text("description").notNull(),
  resolution_notes: text("resolution_notes"),
  reported_by_actor_id: text("reported_by_actor_id").notNull(),
  resolved_by_actor_id: text("resolved_by_actor_id"),
  resolved_at: text("resolved_at"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});



