-- Connection Hub: domínio multi-tenant. Migration local; não aplicada remotamente neste marco.
create table public.integration_connections (id uuid primary key default gen_random_uuid(),agency_id uuid not null references public.agencies(id) on delete restrict,provider text not null check(provider in('google','meta','alastre_ai','electronic_signature','email')),label text,responsible_actor_id uuid references public.agency_actors(id) on delete restrict,credential_ref text,status text not null default 'disconnected' check(status in('pending','connected','attention','expired','revoked','error','disconnected')),last_sync_at timestamptz,next_sync_at timestamptz,last_success_at timestamptz,sync_status text not null default 'idle' check(sync_status in('idle','syncing','success','error')),last_error_code text,metadata jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(agency_id,id),check(credential_ref is null or credential_ref like 'vault:%'),check(jsonb_typeof(metadata)='object'));
create table public.integration_connection_capabilities (id uuid primary key default gen_random_uuid(),agency_id uuid not null references public.agencies(id) on delete restrict,connection_id uuid not null,capability text not null,status text not null default 'pending' check(status in('pending','active','attention','disabled')),granted_scopes text[] not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(agency_id,connection_id) references public.integration_connections(agency_id,id) on delete cascade,unique(connection_id,capability));
create table public.integration_external_resources (id uuid primary key default gen_random_uuid(),agency_id uuid not null references public.agencies(id) on delete restrict,connection_id uuid not null,capability text not null,resource_type text not null,external_resource_key text not null,display_name text not null,parent_external_resource_key text,status text not null default 'active' check(status in('active','unavailable','removed')),metadata jsonb not null default '{}',last_discovered_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(agency_id,connection_id) references public.integration_connections(agency_id,id) on delete cascade,unique(agency_id,id),unique(connection_id,capability,external_resource_key),check(jsonb_typeof(metadata)='object'));
create unique index if not exists clients_agency_id_id_uq on public.clients(agency_id,id);
create table public.client_resource_bindings (id uuid primary key default gen_random_uuid(),agency_id uuid not null references public.agencies(id) on delete restrict,client_id uuid not null,resource_id uuid not null,capability text not null,status text not null default 'active' check(status in('active','inactive')),created_by_actor_id uuid references public.agency_actors(id) on delete restrict,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(agency_id,client_id) references public.clients(agency_id,id) on delete cascade,foreign key(agency_id,resource_id) references public.integration_external_resources(agency_id,id) on delete cascade,unique(client_id,resource_id,capability));
create table public.integration_authorization_sessions (id uuid primary key default gen_random_uuid(),agency_id uuid not null references public.agencies(id) on delete restrict,provider text not null check(provider in('google','meta')),initiated_by_actor_id uuid not null references public.agency_actors(id) on delete restrict,state_hash text not null check(char_length(state_hash)=64),pkce_credential_ref text not null check(pkce_credential_ref like 'vault:%'),return_path text,status text not null default 'pending' check(status in('pending','processing','completed','expired','cancelled','failed')),expires_at timestamptz not null,created_at timestamptz not null default now(),completed_at timestamptz,unique(state_hash));
create index integration_connections_agency_status_idx on public.integration_connections(agency_id,status);create index integration_resources_agency_capability_idx on public.integration_external_resources(agency_id,capability,status);create index client_resource_bindings_agency_client_idx on public.client_resource_bindings(agency_id,client_id,status);
alter table public.integration_connections enable row level security;alter table public.integration_connection_capabilities enable row level security;alter table public.integration_external_resources enable row level security;alter table public.client_resource_bindings enable row level security;alter table public.integration_authorization_sessions enable row level security;
revoke all on public.integration_connections,public.integration_connection_capabilities,public.integration_external_resources,public.client_resource_bindings,public.integration_authorization_sessions from anon,authenticated;
create policy integration_connections_service_only on public.integration_connections for all to anon,authenticated using(false) with check(false);create policy integration_capabilities_service_only on public.integration_connection_capabilities for all to anon,authenticated using(false) with check(false);create policy integration_resources_service_only on public.integration_external_resources for all to anon,authenticated using(false) with check(false);create policy integration_bindings_service_only on public.client_resource_bindings for all to anon,authenticated using(false) with check(false);create policy integration_authorization_service_only on public.integration_authorization_sessions for all to anon,authenticated using(false) with check(false);

-- Vault é a única implementação de credenciais adotada; funções acessíveis apenas ao service_role.
create extension if not exists supabase_vault with schema vault;
create or replace function public.connection_hub_store_secret(p_secret text,p_description text default null) returns text language plpgsql security definer set search_path='' as $$declare v_id uuid;begin select vault.create_secret(p_secret,null,p_description) into v_id;return 'vault:'||v_id::text;end$$;
create or replace function public.connection_hub_get_secret(p_reference text) returns text language sql security definer set search_path='' as $$select decrypted_secret from vault.decrypted_secrets where id=replace(p_reference,'vault:','')::uuid$$;
create or replace function public.connection_hub_update_secret(p_reference text,p_secret text) returns void language plpgsql security definer set search_path='' as $$begin perform vault.update_secret(replace(p_reference,'vault:','')::uuid,p_secret);end$$;
create or replace function public.connection_hub_delete_secret(p_reference text) returns void language plpgsql security definer set search_path='' as $$begin delete from vault.secrets where id=replace(p_reference,'vault:','')::uuid;end$$;
revoke all on function public.connection_hub_store_secret(text,text),public.connection_hub_get_secret(text),public.connection_hub_update_secret(text,text),public.connection_hub_delete_secret(text) from public,anon,authenticated;
grant execute on function public.connection_hub_store_secret(text,text),public.connection_hub_get_secret(text),public.connection_hub_update_secret(text,text),public.connection_hub_delete_secret(text) to service_role;
